### ISSUE TITLE
PDF clipboarded text has tabs where spaces should be

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#102]
Text copied from the PDF to the clipboard has words separated by tabs rather than spaces.

In Linux, I copied some text from the book using left-mouse-highlight and pasted it into vi using middle mouse.  I then saved the vi buffer to a file.  The words in the paste buffer, and therefore the file, are separated by tabs rather than spaces:

```
wayne@mercury:~$ cat /tmp/quote
A   doubly  linked  list    is  exactly the same

wayne@mercury:~$ od -c /tmp/quote
0000000   A  \t   d   o   u   b   l   y  \t   l   i   n   k   e   d  \t
0000020   l   i   s   t  \t   i   s  \t   e   x   a   c   t   l   y  \t
0000040   t   h   e  \t   s   a   m   e  \n  \n
0000052
```

An alternate symptom is that the text pasted from the clipboard has the words run into each other.  It depends upon the application accepting the pasted text whether tabs will show up between words, or nothing.  Pasting the clipboard text into Emacs or shell shows wordsjammedtogether.

This reproduces in both Linux and Windows.

**Comment by wconrad** [comment]
I just found out that this issue affects searching within a PDF too: Phrases cannot be searched for, since I can't (don't know how) to type tabs between the words in my search bar.

**Comment by robconery** [comment]
I can't do anything in terms of how Gitbook does PDFs. I can suggest using epub instead. Also - I'll be moving to a new book generator in a few revs.

**Comment by wconrad** [comment]
Sounds good to me, thanks.
