### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by oferze** [robconery/feedback#103]
**Page 35:** _...in a a few hours..._ - drop the redundant `a`

**Page 41:** _...in inherited from the containing directory_ -> should be "**is** inherited"

**Page 42:** _...this where devices..._ -> should be "this **is** where devices..."

**Page 43:** _...where MongoDB stored it's data._ -> should be **its** and also **stores** (present simple)

**Page 47:** _You can install most anything..._ -> should be **mostly**

**Comment by robconery** [comment]
Thanks - fixed.
