### ISSUE TITLE
Content corrections

### ISSUE THREAD

**Issue by oferze** [robconery/feedback#104]
**Page 42:**

The writing in the graphics somewhat contradicts the sentence just below it.
Does `root` on a Mac actually prevents you from doing any harm? if that's not the case - the sentence needs to be corrected. If it _is_ the case - I would have phrased the sentence differently, such as: _On Macs though, the Unix system is configured in a way such that the `root` user won't let you do any harm_ (but I'm really doubt if that's the case...) so it doesn't contradict the graphics above it.

**Page 43:**

_/opt_ - the end of the paragraph doesn't make sense there; I believe it should read _if it's not in `/bin`, it's typically in the `/opt` directory.

Also, I'd maybe give an example - Redis installs itself under `/opt`. So, it's a binary, but not one that belongs to the "main Linux binaries" hence it's there.

Also, I'd add `/usr/bin` as another directory where binaries reside ,in addition to `/bin`

_/home_ - I'd mention one important characteristic - `~` is the current user's home folder (such as `/home/rob`). So, `cd ~` goes there and it's super handy.

**Comment by robconery** [comment]
Thanks - in the future if you could provide a clearer issue title it would help. Also - it's considered good form to keep one issue per issue. This is just a general Github thing :).

I've fixed the latter bits you suggest (which are duplicates) - thanks for reporting!

**Comment by oferze** [comment]
(Hopefully you'll see this even though the issue is closed:) Yeah I know you usually keep one issue for one issue, I work with GitHub daily :) but this is I believe more true for code where each issue takes a concentrated mental "effort" to understand, fix and implement.

But this is a book... I figured it's less overload for both me and you to see several issues at once. Having said that, I _would_ actually split the above issue to 2 main ones but still keep say all the small corrections about Linux folder structure explanations (Page 43) in one.

**Comment by robconery** [comment]
Good point - I just reread what I wrote and it sounds a bit ... condescending sorry mate. I've been writing non-stop and sometimes I'm far too brief.

Tell you what: _ignore me_. I'm just stoked you're taking the time. I didn't mean to sound shitty :).
