### ISSUE TITLE
SSH authorized_keys permissions for setting up a server

### ISSUE THREAD

**Issue by bdewater** [robconery/feedback#105]
I don't have an Ubuntu box ready to test, but on a CentOS 7 server I recently set up I had to change te permissions because SSH otherwise wouldn't allow me to connect with keys:

```
chmod 600 .ssh
chmod 700 .ssh/authorized_keys
```

**Comment by robconery** [comment]
I'll be redoing the linux chapter to be a bit more focused in this way.
