### ISSUE TITLE
pdf pg 60, code examples need prerequisites to be usable

### ISSUE THREAD

**Issue by joshcrews** [robconery/feedback#107]
<img width="775" alt="sql" src="https://cloud.githubusercontent.com/assets/87632/18014674/a221d304-6b89-11e6-8f41-17d296c3ee8b.png">

I want to be able to follow the examples typing them out in my shell, but the leap into psql commands on databases I don't have breaks that.

Recommended: switch to command examples without prerequisites, or provide the prerequisites

**Comment by robconery** [comment]
I wanted to keep this "real" and, as you can see in the chapter, I'm using a database example throughout. 

So I can solve this by 1) showing you how to install PostgreSQL or 2) do as you suggest, which is to redo the demo set entirely.

For me the easier (and far better) solution is to have a quick blurb about "if you want to follow along with the below, let's take a few seconds and install PostgreSQL".

**Comment by robconery** [comment]
Added blurb... also I'm reworking this entire chapter so installing PostgreSQL will be part of a walkthrough.
