### ISSUE TITLE
Quick sort chapter mistake

### ISSUE THREAD

**Issue by aneshas** [robconery/feedback#109]
Where it says: 

“The neat thing here is that there are no numbers **less** than 8 in our list on the right, so there's nothing we need do.”

It should say:

“The neat thing here is that there are no numbers **GREATER** than 8 in our list on the right, so there's nothing we need do.”

**Comment by robconery** [comment]
Cheers fixed - thanks :).

**Comment by aneshas** [comment]
np ;)
