### ISSUE TITLE
make example on P102 of PDF

### ISSUE THREAD

**Issue by superfell** [robconery/feedback#110]
on Page 102 of the PDF there's an updated version of the makefile to use $@, 

```
dist:
    @ mkdir $@
```

but you still have a DIST variable, if the DIST variable is changed to something else, e.g. DIST=distrib, then the dist target doesn’t do the right thing, i think you need to keep 

```
dist:
     mkdir $DIST
```

**Comment by robconery** [comment]
I think the better way is to:

```
all: $(DIST) app.js

$(DIST):
    @ mkdir $@
```

**Comment by robconery** [comment]
Also - this is fixed :)
