### ISSUE TITLE
Suggestion: Mention or add a reference to the Filesystem Hierarchy Standard

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#112]
_Section_: Who, What, Where?
_Page_: 39
_Format_: PDF

> Linux machines have a standard directory structure, although people have
> arguments as to what should go where. You should understand the basics, at the
> very least, so you can avoid a bad situation.

I think that you should at least mention the _Filesystem Hierarchy Standard_ as a reference.

**Comment by robconery** [comment]
Removing Linux bits, but this is a great idea.
