### ISSUE TITLE
About sudo

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#113]
I think that you should mention some other benefits from `sudo` in the _ROOT AND SUDO_ section (page 40 of the PDF version), for example:
- Each command that you run with `sudo`, will be logged in `/var/log/auth.log`
- With `sudo` you can define a more fine-grained security policy
- There is no need to share the `root` password
- You don't need to type the password every time, the authentication automatically expires after a couple of minutes, but you can configure this value.

Also, in the _Setting Your Account as a Super User_ section, there is no need to modify the `/etc/sudoers` file with `visudo` because there is a rule in that file that allow us to take a shortcut, the rule is the following:

```
# Allow members of group `sudo` to execute any command
%sudo   ALL=(ALL:ALL) ALL
```

With that rule in mind, you can do the following:

```
# usermod -a -G sudo rob
```

Or, even easier, you can use `adduser rob sudo`, which adds an existing user to an existing group.

HTH

**Comment by robconery** [comment]
This is a great suggestion but I think I'm removing the Linux stuff - it's kind of outside the book.
