### ISSUE TITLE
Typo: Unbuntu

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#114]
Format: PDF, Page: 89

> If you head over to nodejs.org you can find the script for installing NodeJS on
> Unbuntu:

`s/Unbuntu/Ubuntu/`

**Comment by alj1s** [comment]
Duplicate of #24

**Comment by robconery** [comment]
Crazy that I would let that slip through... but I think it's common :). This has been fixed and yes, it's a duplicate.
