### ISSUE TITLE
Adding an ssh key with ssh-copy-id

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#115]
Format: PDF, Page: 91, 92

> Open up a new tab on your local machine and output the contents of your key to
> the screen. You should know how to do this - it's the cat command:
> 
> `cat ~/.ssh/id_rsa.pub`
> 
> Copy the contents you see there. If you don't have an SSH key, head back a few
> chapters and follow the steps there.
> 
> Now, switch back over to the tab for our remote server. Press "i" for "insert" in Vim. Paste your key in here, and then hit "escape". To save a quit Vim type :w:q .
> 
> Great. You now have a file called "authorized_keys" which tells SSH that users with
> that key are allowed to login. Only one more step here, which is to make sure that
> the deployer account owns this file. If they don't, you'll get a permissions error:
> 
> `chown -R deployer /home/deployer/.ssh`
> 
> The chown command means "change owner" and -R means "recursively" - so all
> subfiles and directories will have their ownership changed. The next argument is
> who the new owner is, then finally the directory.

As a suggestion, you should use `ssh-copy-id` instead, this script will copy your local public key to the remote-host `authorized_keys` file. Also, `ssh-copy-id` will set the proper permission for `~/.ssh` and `~/.ssh/authorized_keys` in the remote server.

HTH

**Comment by robconery** [comment]
I'l add this as a second step - but I think it's important to understand what's happening under the hood.

**Comment by milmazz** [comment]
I agree, we should always try to know what happens under the hood, you could add this alternative as a "pro-tip" section or something similar, whatever work best for you :)

The only missing thing in the original instructions (v.002) is how to set the proper permissions for `~/.ssh` and `~/.ssh/authorized_keys`, but if I recall well there was a ticket that already mention this.
