### ISSUE TITLE
make && make install

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#116]
Format: PDF, Page: 97

> Have you ever downloaded software from source onto a Linux box and had to run
> `make && make install` ? This is why. The downloaded source (usually C or C++) is
> compiled and then installed wherever binaries go in the system. Do you remember
> where that is? Yep: `/opt`

I think that the correct answer is `/usr/local` in this case. According to the [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html#USRLOCALLOCALHIERARCHY)

> The `/usr/local` hierarchy is for use by the system administrator when installing software locally. It needs to be safe from being overwritten when the system software is updated. It may be used for programs and data that are shareable amongst a group of hosts, but not found in `/usr`.
> 
> Locally installed software must be placed within `/usr/local` rather than `/usr` unless it is being installed to replace or upgrade software in `/usr`.

HTH

**Comment by robconery** [comment]
Thanks - fixed.
