### ISSUE TITLE
Page 41 to 42 bridge is confusing (pre_002)

### ISSUE THREAD

**Issue by BradleyJohnson** [robconery/feedback#119]
> The super user `root` owns the file, but the group is `staff`.

-> 42

> As it turns out, this is the `/bin` directory, owned by the system god, `root`. Most of the core applications and programs are in there ("cp", "ls", "cd", etc), including the system bootup.

I'm confused how `/bin` enters the picture here, though I am an impostor myself so maybe I'm missing something obvious here? Then again, that may mean I'm a good canary for the situation.

**Comment by robconery** [comment]
This, unfortunately, is a problem introduced by me when I tried to expand on a previous topic - it orphaned what we were doing.

I'm fixing this currently.

**Comment by robconery** [comment]
Fixed by moving entire Linux chapter into Addenda and added walkthroughs

**Comment by BradleyJohnson** [comment]
Great, and thanks for working on this project! I've been thinking about how
the world needed a book like this for some time :grin:
