### ISSUE TITLE
setting up web server: specify what goes into app.js

### ISSUE THREAD

**Issue by FrauBienenstich** [robconery/feedback#120]
I stumbled upon this while going through the set up. I think for the sake of completeness somewhere around page 90, after having installed npm, it would make sense to explicitly say what should go into the app.js file on the server, ie how to set up a http server in node.

This is a great project, btw. I really enjoy reading your book! 😃

**Comment by robconery** [comment]
Yeah - this walkthrough needs a shakedown. I'll be redoing it entirely - so I'm closing this for now :).
