### ISSUE TITLE
Primary keys and O(1)

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#121]
Format: PDF, Page: 125

> If you're accessing arrays, the most efficient (and least complex) thing you can do is
> to access an element by index position. This operation is O(1).

I think is worth mentioning or clarify that you're referring to the _Array_ data structure, which normally is implemented as a _list of items in consecutive memory locations, one node after the other_. So, you can say that `location(X[index]) = location(X[0]) + size(datatype) * index`, in this case, `location(X[0])` is a constant that represents the _base address_.

But in other languages (e.g. Elixir), you may find that the _list of items_ is implemented as a _Linked List_, in those cases, accessing an element by index position is an `O(n)` operation.

HTH

**Comment by robconery** [comment]
I was wrong about PKs and O(1) - which I've fixed already for the next release.

I think it's confusing to conflate "array-like" with the Array data structure - I think people will understand when I use the word "arrays" that I'm referring to "arrays".

Bringing up Elixir and lists is a kick to the hornet's nest; maps, lists, keyword lists - they are all abstractions on Erlang types and if I use `Enum.at` - I do believe that's a O(1) op. Same with a map: `my_map.thing` is a O(1) accessor.

**Comment by milmazz** [comment]
> I think it's confusing to conflate "array-like" with the Array data structure - I think people will understand when I use the word "arrays" that I'm referring to "arrays".

Ok

> they are all abstractions on Erlang types and if I use Enum.at - I do believe that's a O(1) op.

No. Actually is you read the docs of the `Enum.at/3` function, you'll see the following note:

> Note this operation takes linear time. In order to access the element at index
> index, it will need to traverse index previous elements.

or this:

> In both Enum and List modules, any kind of index access on a list is linear.
> Negative indexes are also supported but they imply the list will be iterated
> twice, one to calculate the proper index and another to perform the operation.

If you check the documentation for the `List` module.

HTH

**Comment by robconery** [comment]
Fair enough - thanks for the clarification RE `Enum.at` - I was thinking I should check that :). Either way I don't see how a discussion on Lists in Elixir (or other languages) clarifies the discussion on arrays. I also think that using the word "arrays" make it clear I'm discussing arrays in terms of the data structure.
