### ISSUE TITLE
P = NP? Missing or invisible characters?

### ISSUE THREAD

**Issue by alj1s** [robconery/feedback#124]
I couldn't see this as an existing issue (closed or open). Apologies if it is a duplicate.

In the ASKING THE QUESTION: HOW HARD CAN IT BE? section, the fourth paragraph reads,

"If I asked you to sort N cartons of milk in terms of "sourness" using  merge sort it would take you O(n n) seconds"

It should be O(n log n).

I'm reading the pdf on a Mac (using Preview).

**Comment by robconery** [comment]
Yeah - the encoding got borked. Thanks though!

**Comment by robconery** [comment]
Fixed...
