### ISSUE TITLE
P = NP? Polynomial formatting

### ISSUE THREAD

**Issue by alj1s** [robconery/feedback#125]
In the ASKING THE QUESTION: HOW HARD CAN IT BE section. The fifth paragraph copies text from wikipedia to give examples of polynomial equations. But the exponentiation is not formatted correctly.

So terms such as x^2 are written as x2

Viewing the pdf on Mac OSX using Preview.

**Comment by robconery** [comment]
Yep - thanks. This is a dup so closing...

**Comment by alj1s** [comment]
Oh, sorry. I missed it.
