### ISSUE TITLE
Can't copy code examples in PDF

### ISSUE THREAD

**Issue by marcusoftnet** [robconery/feedback#126]
Love the book!

I have a problem to copy any text from the PDF (for example the examples) to my clipboard. 

I can select the code gists and copy it but it only places an empty string in my clipboard. 

Using a Mac and reading the PDF with Preview.app

**Comment by robconery** [comment]
Thanks - I hate to do this to you but this isn't an issue with the book, per se. I can't really troubleshoot your PDF/Copy/Paste situation - but I can suggest that you clone the repo with the samples and just use the code there.

**Comment by marcusoftnet** [comment]
No problems at all. Just wanted to check if there's a general problem or not. I'm fine using the git repos
