### ISSUE TITLE
complexity graph axes incorrect

### ISSUE THREAD

**Issue by pjbirch** [robconery/feedback#127]
imposter_pre_002.pdf, p132
Complexity graph seems to be incorrect.

The graph shows number of operations (n) on the vertical axis vs. time (t) on the horizontal.  Generally, complexity in time would show how time increases as the number of operations (n) increases, therefore, the axes should be reversed (i.e. time on the vertical vs. n on the horizontal).

Because the axes are reversed, the direction of the O(n^2) graph is incorrect.  O(n^2) increases in time exponentially against n.  The graph shows this as the inverse.

**Comment by robconery** [comment]
Yep - this was reported but thanks! Closing as dup...
