### ISSUE TITLE
Clarify description of Binary Search Tree

### ISSUE THREAD

**Issue by pjbirch** [robconery/feedback#129]
imposter_pre_002.pdf, p132
The description of a Binary Search Tree needs enhancing.  Maybe add the rule that each node can have a maximum of two sub-trees (left and right).  

Also, clarify your decision on why you substituted 15 in place of 13.  As I see it, you could also have replaced 13 with 12, and the tree would still be valid.

**Comment by robconery** [comment]
Thanks - in terms of enhancing, you say "maybe add..." and I'm happy to do so... but this leaves me wondering if these are two problems you want fixed, or if there's a general "do more" feeling.

**Comment by pjbirch** [comment]
Yes, sorry, I should be clearer.  My first paragraph is really a "do more" feeling: I feel that it needs a little more clarification to distinguish a binary tree from a heap (tree) that can have many child nodes.  Maybe it becomes clearer once a reader has read the later paragraphs around searching.

My second paragraph was a suggestion for my own understanding, as it seems that you are saying that after removing node 13 from the tree that the only choice is to lift node 15 in its place. However, I don't see that it's the only choice, as unless I'm missing something, you could choose to lift node 12 and it would be just as valid. However, it could be my lack of understanding.

**Comment by robconery** [comment]
Thanks - no you're right (I think) :):) that 12 or 15 would work. I've added a blurb on the rules and I also stated that 12 or 15 could take its place.
