### ISSUE TITLE
PDF p. 290 aggregation: Mention count(*)?

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#130]
On PDF P. 290, "AGGREGATION":

> `select   count(1)    from    users;`
> I'm   using       count(1)        here    for simplicity  -   it  won't   affect  the result. I   could   use
>   count(id)       or  anything    really.

SQL standard is to use `count(*)` when counting records.  `count(1)` also works, and has the same performance because SQL engines have been taught to recognize this common idiom, but `count(*)` is--I think--canonical.  Also, it is not strictly true that you can necessarily use anything else: I can imagine `count(some_function())` having lower performance.

StackOverflow has a nice discussions of `count(*)` vs. `count(1)` [here](http://stackoverflow.com/questions/1221559/count-vs-count1).

I don't mention all this because I think the book should get into this discussion--it shouldn't.  But I think it _should_ at least mention count(*) here, since it's commonly used.

**Comment by robconery** [comment]
I'll tighten up the wording - the _or anything_ part isn't completely true... but I also think a purposeful use of a function is a little far-fetched. Also: in the SO link the author mentions that `count(1)` has been optimized by some vendors.

**Comment by wconrad** [comment]
Rob,

I just finished my first pass through the book (there'll be another
pass--there's a lot here that's worth re-reading and asking the web
about).  What a wonderful work you've created.  I can't even imagine how
much sweat went into that.  Well done, and thanks!

Wayne Conrad
