### ISSUE TITLE
PDF p. 315: Does PostgreSQL parallelize yet, or doesn't it?

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#131]
On PDF p. 315, under "Tech  Review  Note    From    Craig   Kerstiens", you quote Craig as saying that PostgreSQL does not parallelize workloads yet.  But then you quote the Wiki, which mentions that version 9.6 does parallelize workloads.  This is confusing--it sounds like the book is saying that it doesn't _and_ it does--unless you know one additional fact not mentioned in the book: That version 9.6 is still in beta.  Perhaps something like this would remove the confusion:

> Craig writes "YET" because PostgreSQL version 9.6, currently in beta, does parallelize workloads.  From the PostgreSQL Wiki:

**Comment by robconery** [comment]
Yep - added thanks.
