### ISSUE TITLE
Revise graph for O(n) and O(n log n) and consider axis labels on page 132

### ISSUE THREAD

**Issue by mladenrajic** [robconery/feedback#135]
Please note that O(n log n) should be take more time to execute than O(n) and graph is now showing that.  Also, lets consider graph axis labels by looking at the O(n^2) case. The way it is presented on page 132 i would read it as if i increase in Operations(n) by large factor my time would be increased by tiny increment = large delta on Operations(n) produces Small increment in time. It looks like axis names are reversed?

**Comment by robconery** [comment]
Closing this as duplicate - the graph is incorrect as it indicates time when time is not a factor.
