### ISSUE TITLE
PDF p. 421: Syntax error in Ruby "responds_to" example

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#136]
On PDF p. 421, This Ruby snippet has a syntax error:

```
if  thing.responds_to   <<
                #   do  the append  op
end
```

(Sorry about the tabs; they are a cut/paste artifact)

The method name `<<` should be a symbol (`:<<`) or a string (`"<<"`)

**Comment by robconery** [comment]
Thank you! Fixed :)
