### ISSUE TITLE
Images work weirdly in ePub using iBooks dark mode

### ISSUE THREAD

**Issue by metamoof** [robconery/feedback#137]
Hi, 

iBooks reader on iPad and iPhone automatically switches to dark mode when the lighting is low.

By accident I spotted this issue with an image, where it seems to be out of its frame...

![image](https://cloud.githubusercontent.com/assets/805751/18157173/09367e5a-701c-11e6-8ef0-cf51c01b4ed4.png)

Also, the chapter number doesn't change colour.

**Comment by robconery** [comment]
Yep - this has been reported (and thanks)...
