### ISSUE TITLE
Typo: GNU\/Linux in ePub

### ISSUE THREAD

**Issue by metamoof** [robconery/feedback#138]
Hi, 
I'm reading the book in iBooks, and I've spotted that you are occasionally referring to GNU\/Linux instead of GNU/Linux. Example:

![image](https://cloud.githubusercontent.com/assets/805751/18157580/9d88bbd4-701e-11e6-8b43-5f1634f2fae3.png)

**Comment by robconery** [comment]
Yep - reported and fixed thanks :).

**Comment by adrianovieira** [comment]
This also happens on PDF file (v0.0.2).
