### ISSUE TITLE
Algorithms vs patterns

### ISSUE THREAD

**Issue by sabarnett** [robconery/feedback#14]
Not sure if this is just my uncertainty about my skill set, but it might be nice to have a short section on the difference between algorithms and patterns and why I feel such a bad programmer because I can't recite the entire list of patterns. Algorithm seems to have become a dirty word in our OO oriented world yet so much of what we do depends on them.

**Comment by robconery** [comment]
Interesting - can you give me more of a background on this? I never saw a relationship here so I'm not too sure how to phrase it.

On a related note: I'm thinking about adding a "So and So Asked:" blurb as I'm getting a number of questions (like this one) - I'd love to use this question because it's useful and it helps others to see that "they're not the only ones" if you will :).

**Comment by sabarnett** [comment]
No problem. First thing to know is that I'm old. I cut my teeth on S/370 assembler, so many people look on me as a dinosaur. I have progressed through over 20 programming languages, ending up with VB6 and C#. I'm currently on a project to write a SPA using .net core and angular 2 (I got on the project because I've created a couple of static web sites using bootstrap). 

When I approach a problem I do so by thinking through the things it needs to do and modularising them in to discrete units of functionality. I then apply one or more algorithms to solve those problems and plug it all together to a final solution. In my addled old brain, I see no difference between this and what the 'modern children' do when they apply patterns to a problem.

So, I'm obviously missing a point as my younger colleagues cannot conceive of using an algorithm to solve a problem and talk to each other in pattern speak. I suspect that, were I a new developer just getting a degree in computing, I might be able to have that same conversation, but I am entirely self taught and feel I must be missing out on something. I really do feel like an impostor at a design meeting because I see software in practical terms and others see it as a series of patterns with no thought to how they might fit together.

The really strange thing is that we often end up with very similar solutions, so I just don't get why algorithms are laughable to younger developers and patterns are King. 

Like I said, I'm old.

Steve Barnett
steve@sabarnett.co.uk

**Comment by robconery** [comment]
It sounds to me like you're thinking of higher-level algorithms? The ones I do in the book are just the classics - various sorts and searches. We use these every day but they're kind of baked into frameworks and we don't really think about it very much.

If you don't mind - can you give me an example of your process a bit more?

**Comment by sabarnett** [comment]
Probably the most recent was a small application I put together to organise my work. It's a simple hierarchical structure of notes which I needed to persist to disk in such a way that it maintained its structure. The simplest way to represent this was a standard tree structure with each node having a pointer to its parent, siblings and first child. So I used standard tree structure algorithms to implement this structure.

I had cause to present this to a colleague who couldn't grasp the algorithm because they could not equate it to one of the patterns they had been taught and, if it didn't match a pattern, it had to be wrong. 

As you say, a lot of algorithms are baked in to a framework, which is great when you have a framework. What I am learning right now is that I now have to write JavaScript and the nice stuff baked in to .net isn't there any more. A familiarity with algorithms, what they do, where they are appropriate and how to modify them becomes more useful. 

I suppose the point I am making is that we are becoming reliant on patterns and forgetting that there are alternative approaches to structuring a program. We're I less of an old fogey and were a new developer who had been (correctly) taught to think in patterns, I believe a knowledge of algorithms is a complementary skill that will not be taught to any degree by a modern programming course.

If you don't think it'll fit the book, please feel free to say so. 

Steve Barnett
steve@sabarnett.co.uk

**Comment by robconery** [comment]
I'll see if I can work this into some updates I'm doing to the patterns bits.
