### ISSUE TITLE
logx y=3 should be x log y =3

### ISSUE THREAD

**Issue by mountain65** [robconery/feedback#140]
On location 2230 on the Kindle just before the graph you write

> So, if I write x3 = y, then I can say logx y = 3. You can visualize this on a graph if it makes it easier:

It should be "x log y = 3" I think. Superscript would help readability big time. Otherwise my proposed change could be interpreted as x times log y. So <sup>x</sup>log y, since that works in Markdown!

**Comment by robconery** [comment]
I think this is a Kindle issue - here's the passage in Markdown:

```
So, if I write x<sup>3</sup> = y, then I can say log<sub>x</sub> y = 3.
```

Not sure why it didn't get transcribed the right way.

**Comment by jeffweiss** [comment]
I concur that this seems to be a Kindle-specific issue.

# ePub

![screen shot 2016-09-06 at 2 17 59 pm](https://cloud.githubusercontent.com/assets/818053/18291551/2d599c52-743d-11e6-87a2-49013cf147c4.png)

# Kindle

![screen shot 2016-09-06 at 2 19 20 pm](https://cloud.githubusercontent.com/assets/818053/18291537/18d346ac-743d-11e6-8723-0a2ea0bf6dee.png)

**Comment by robconery** [comment]
Hmmm. Well... shoot. Not sure what to do about this...

**Comment by jeffweiss** [comment]
@robconery It looks like `<sup>` requires additional CSS for Kindle. https://kdp.amazon.com/community/message.jspa?messageID=1038253
¯\_(ツ)_/¯

**Comment by robconery** [comment]
I'm moving the editing process to Scrivener which has an equation editor - I'll use that and hopefully it will fix this problem.

**Comment by robconery** [comment]
I redid this using different notation. Kind of a bummer...
