### ISSUE TITLE
Big 0 Graph Issues

### ISSUE THREAD

**Issue by iandanforth** [robconery/feedback#143]
Version: pre 002
Page: 132

Ref: http://bigocheatsheet.com/
1. X axis should be "elements" not "time"
2. (Nitpick) The O (n log n) line should never decrease.

The endpoint of the line appears to be below the highest point on the line. While this is a handdrawn chart, you may want to carefully avoid giving the impression that there is a number of elements, after which, the number of operations required starts decreasing.

**Comment by robconery** [comment]
Yeah thanks - this has been reported and is fixed. Cheers :).

**Comment by iandanforth** [comment]
Sorry I'll double check closed issues!

**Comment by robconery** [comment]
No problem at all! Glad you're catching things :).
