### ISSUE TITLE
minor typo in Linux section

### ISSUE THREAD

**Issue by chrisosaurus** [robconery/feedback#144]
on pages 29 and 30 you have two instances that says GNU\/Linux rather than GNU/Linux, notice the extra backslash

> ... So, if you hear someone refer to GNU\/Linux -
> ...
> ...  system that GNU\/Linux was
> ...
> referring to a GNU/Linux machine.

I'm reading through imposter_pre_002

**Comment by robconery** [comment]
Yep - reported and fixed... thanks :)
