### ISSUE TITLE
Some Unix Issues

### ISSUE THREAD

**Issue by akivascript** [robconery/feedback#150]
• Page 24: OS X (now macOS) is not based on the Linux kernel but is, instead, based on FreeBSD. The Sony Playstation also runs FreeBSD under the hood. So the sentence 'Not the pretty interface provided by your beautiful Mac' doesn't make sense since OS X isn't Linux at all.

Also, Linux is not the center of technology, it's Unix of which Linux is a flavor. You're likely to find a variety of Unixes in operation behind the scenes so to say it's all Linux is erroneous. You touch on this on page 30. I also wouldn't say Linux was designed to replace Unix but proper Unix is proprietary and expensive (and, at the time, I'm not sure if a version of Unix existed for PCs yet; certainly not a free one). Linus made Linux free and a few years later, FreeBSD was released, too. 

I'd change your suggestion on Page 34 as upstart has been abandoned by Ubuntu since 16.x for systemd. This bit me when I built out a new server at Digital Ocean and upstart wasn't there (even though, confusingly, an `/etc/upstart` directory full of stuff exists. I much prefer systemd, by the way.

Another thing, have a look at http://www.fishshell.com. It's modern, colorful, and rejects a lot of BASH-style traditions. It even comes with a web instance for configuration. Fantastic for people new to Unix and it's powerful enough for the hardcore; I learned Unix in the late 80s and used tcsh forever, then z-shell, and now I have fish everywhere. I don't know one single soul who uses Korn.

Also, although `visudo` is perfectly reasonable, you can also use `gpasswd -a [username] sudo` to add an account to the sudo group without having to fuss with an editor. Speaking of quitting Vim, by the way, you might want to mention `ZZ` which, of course, does the same thing as `:wq`. It's just quick. Also, you should mention Emacs. I was a vi/vim user since the birth of the solar system but converted a year or so ago because of Spacemacs: all the power of Emacs with all the power of vim.

If this is far too much detail, let me know and I'll relent. I just happen to know a lot about Unix. I am very much enjoying the book, by the way. I am the exact target audience: I'm a total auto-didact with no CS background at all yet I've somehow been developing professionally for 16 years. And I'm pals with Scott Hanselman on Twitter, too! Small world.

Hope this helps.

**Comment by robconery** [comment]
Really really appreciate the fine detail here - thank you! Each of these issues has been reported and I've gutted the Linux stuff and removed it entirely, which was great feedback! I'll add it back in slowly in the form of addendum/walkthrough - but the next drop will see more Comp Sci, less Linux :).
