### ISSUE TITLE
typos on page 46

### ISSUE THREAD

**Issue by CarteriTrellis** [robconery/feedback#152]
This is in version 0.0.3. In the paragraph immediately under the graph on page 46:

"Here we see that the O(_n_^2) operations increase exponentially and _n_ increases."

You have "and" instead of "as" and it should read "...exponentially as _n_ increases."

In the same paragraph:
"However O(log _n_) (and _n_ log _n_) decrease _logarithmically_ over time."

I suspect that should be "...increase _logarithmically_ over time."

**Comment by robconery** [comment]
Thanks! All fixed
