### ISSUE TITLE
Typo in code sample on page 44 (v0.0.3)

### ISSUE THREAD

**Issue by brianloveswords** [robconery/feedback#155]
![screenshot of code sample from book](https://cldup.com/OdtNl8jziV.png)

I believe that fourth line is missing the equals sign,

``` js
var occurrenceCount = db.getOrderItemsWithSkus("X", p.sku);
```

**Comment by robconery** [comment]
Thanks - I removed this :).

**Comment by robconery** [comment]
Oops - meant to say I fixed it :)
