### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by stereobooster** [robconery/feedback#156]
B-tree and binary tree are not the same thing. Chapter when you describe binary tree (heap), but then mention BTREE index in Postgres. 

Big-O describes number of steps required to do an action, it is not always correspond to speed. If there is disk reads involved algorithm can be pretty slow. From my POV you need explicitly mark that fact. `O` shows how much it can be bad in sense of number of steps, but on practice it can be even worse. If your instructions and data doesn't fit into L1, L2, L3, RAM, disk - every time speed drops by magnitude. That's why B-trees are so good for DBs they store info in packets, and when you need an record you read all the packet (computer will did it anyway, it designed read by packets), so you can scan packet in a memory. Less reads from disk, more speed.

**Comment by robconery** [comment]
Is this the paragraph in question?

> Heaps are used in data storage, graphing algorithms, priority queues and sorting algorithms. One of the most popular applications is in Binary Trees, which are used in indexing and also data storage for databases such as MongoDB and PostgreSQL.

I know BTREE/Binary Tree aren't the same thing - I don't see how I made that assertion here. 

> Big-O describes number of steps required to do an action, it is not always correspond to speed. If there is disk reads involved algorithm can be pretty slow. 

In my mind a task is a task, how you go about that task with a given algorithm is the question. Sorting and searching might hit the disk, they might not - it has nothing to do with the complexity of the algorithm you choose. I don't know if I see a reason to convolute the issue.
