### ISSUE TITLE
Big-O discussion and section errors

### ISSUE THREAD

**Issue by chrisosaurus** [robconery/feedback#157]
I think the current explanation of O(1) feels insufficient and I wanted to have a broader discussion about the big-O coverage as a whole.

I haven't finished reading this section, but these are my thoughts so far.

> The simplest possible routine you can write is O(1). This is a static routine, which
> means the function you write will do one thing always, no matter the executions
> involved.

what O(1) runtime really means is that our runtime doesn't scale proportionally to our input size.

If we think to your cat examples, say your house has 6 rooms (our input size is 6) and the cat loves to hide your shoes around the house.
Thankfully our cat only ever hides the shoes in 3 spots, no matter what, so looking for our shoes only ever involves checking those 3 places.
We then renovate our house adding on 12 more rooms, so we now have 18 rooms in our house, however our cat is picky - it still only hides the shoes in 3 places.
So even though our house size has changes from 6 to 18, the runtime of our lookup function is still 3 - since our lookup function's runtime hasn't changed despite the fact our house size (input size) has changed.

Another example would be to always buy the 14th cat you saw, no matter how many cats we see (could be 1,000,000) we will still always purchase the 14th cat.

O(n) on the other hand would be if our cat always has 2 hiding places in every room, so as our house goes from 6 rooms to 18 rooms our search cost goes from 12 (6_2) to 36 (18_2).

Big-O is always about how something (runtime, memory consumption) scales with a range of possible input ranges.

Big-O isn't overly useful for talking about a single fixed N.

Wikipedia says https://en.wikipedia.org/wiki/Big_O_notation

> In computer science, big O notation is used to classify algorithms by how they respond to changes in input size, such as how the processing time of an algorithm changes as the problem size becomes extremely large

The section on O(n^2) is quite good, the cat example works well here, although I think the explanation could be clearer.

> For every cat that comes over, we need to check our list n times to be sure they get
> along [...]

is a little unclear, I think it could be made clearer by specifying exactly what we are checking, maybe something like

"So for each cat that comes over, we need to check to see if it gets along with every other cat that is already there.
So if we have 3 cats over, and a 4th shows up, we now have that check this new cat (Bob) against the 3 cats already there (Susan, Mary, Jeremy) to make sure Bob wont cause a fuss."

I understand the intended audience for this book, and I also understand how hard it is to explain these concepts :)

Your graph showing O(n^2) vs O(n) vs O(nlogn) is actually incorrect.
You show O(nlogn) as growing slower than O(n), but nlogn is bigger than n - by a factor of logn.
I think your graph is incorrectly labelling O(logn) as O(nlogn), and missing a line for O(nlogn)

If our N is 100 then
O(1) = ~1
O(logn) = 6.6
O(n) = 100
O(nlogn) = 100 \* 6.6 = 660
O(n^2) = 100 \* 100 = 10,000

Here is a graph showing these 4 functions

https://www.desmos.com/calculator/kgwiv5zizm

Blue is O(logn)
Red is O(n)
Purple is O(nlogn)
Green is O(n^2).

**Comment by chrisosaurus** [comment]
In the P=NP section you also mention

> If I asked you to sort N cartons of milk in terms of "sourness" using merge sort it
> would take you O(n n) seconds.

However the average and worst cases for mergesort are both O(nlogn)

http://bigocheatsheet.com/
https://en.wikipedia.org/wiki/Merge_sort

I would also recommend being careful using a phrase like "O(n) seconds", as that is starting to blur the line between big-O and exact analysis.

I'll try think of how to potentially rephrase this...

**Comment by robconery** [comment]
First - I need to know the version and format you're reading. The merge sort example you reference here was a typo missing the `log` in the middle of the two `n`s. We agree on that - so I'll just gloss over that for now. I just release 0.0.3 and that _should_ be fixed in there.

For the first comment - I'm having a pretty hard time distilling what your point is, but I'll do my best. 

> what O(1) runtime really means is that our runtime doesn't scale proportionally to our input size.

I think you mean the opposite of what you wrote - that the algorithm we're using will scale almost perfectly (flat line) with our inputs. The amount of inputs don't necessarily matter - the operation involves a single element. Is this what you mean to say? If so - we agree and I think that's what I wrote.

> Thankfully our cat only ever hides the shoes in 3 spots, no matter what, so looking for our shoes only ever involves checking those 3 places.

This is O(n), not O(1) because in the worst case scenario you have to search 3 locations. O(1) is a single operation - unless I misunderstand you. So if the cat hides the keys under my bed _every time_ we just go there, no matter the rooms in our house.

> O(n) on the other hand would be if our cat always has 2 hiding places in every room, so as our house goes from 6 rooms to 18 rooms our search cost goes from 12 (62) to 36 (182).

That would be O(n), yes. A linear scaling.

> Your graph showing O(n^2) vs O(n) vs O(nlogn) is actually incorrect.

In v2 and below, yes it sure was. I conflated time in there which I shouldn't have. I suspect that you're reading an out of date version. If you let me know your email I'll be sure to send an update.

**Comment by robconery** [comment]
Whoops - didn't mean to close.

**Comment by chrisosaurus** [comment]
I am reading imposter_pre_002.pdf which I downloaded from Gumroad immediately before writing this issue.
is Gumroad out of date?
did it serve me the wrong download?

I can't seem to find any internal version within the handbook.

Glad to know the mergesort was a typo, that is what I suspected.

Likewise glad the graph has been corrected.

> I think you mean the opposite of what you wrote - that the algorithm we're using will scale almost perfectly (flat line) with our inputs. The amount of inputs don't necessarily matter - the operation involves a single element. Is this what you mean to say? If so - we agree and I think that's what I wrote.

O(1) doesn't have to involve "a single element" or even "a single operation".

Big-O is talking about the complexity (in this case, runtime) when compared to our input size (n), and how that complexity changes as our n changes.

O(1) runtime means that our runtime doesn't scale proportionally to our input size, that is if our algorithm takes 10 seconds with an input of 1 and 10 seconds with an input of 1000000, then it is (probably) O(1).

> This is O(n), not O(1) because in the worst case scenario you have to search 3 locations. O(1) is a single operation - unless I misunderstand you. So if the cat hides the keys under my bed every time we just go there, no matter the rooms in our house.

Is incorrect.
You could say this is 3 operations, but 3 is a constant factor, and in Big-O we eliminate constant factors - therefore this is O(1)

Searching 3 locations in the worst case is still O(1), since the number of locations we need to search is fixed - it isn't based on our input size (n).

I very politely suggest that I think you are misunderstanding what O(1) means: it doesn't mean "one" anything, it means _constant_ with respect to input size - that is changing our input size doesn't change the cost.

For example if we define a function which calculates the maximum number from the first 3 elements of any array, no matter what size, then this is still O(1)

In python

```
from math import max
def max_first_3(arr):
  if len(arr) < 3: # throw exception
  a = arr[0]
  b = arr[1]
  c = arr[2]
  return max(a, max(b, c))
```

this always does 3 array accesses - each O(1)
it then makes two function calls - also (1)
and the runtime of max is O(1)
therefore the total cost of this function (abusing notation) can be seen as
1 + 1 + 1 + 1 + 1 = 5 operations
and since this is big O we drop all constant factors, so instead of being 5 \* 1 this is just O(1)

If we give an array of 10 items then this takes 5 operators
if we give an array of 1,000,000,000,000 items then this takes 5 operations

Thus the number of operators this takes is a _constant_ and doesn't scale with input size.

This is the definition of O(1).

Another example of constant factors being dropped is if we have a function finds the min and max of an array naively

```
def min_and_max(arr):
  min = arr[0]
  for item in arr:
    if item < min:
      min = item

  max = arr[0]
  for item in arr:
    if item > max:
      max = item

  return (min, max)
```

this function has 2 for loops, each for loop goes over n, therefore each for loop is O(n).

Since this overall function has 2 n loops within it, the overall cost is n+n or 2n

In big-O however we drop any constant factors, so this is still just O(n).

NB: I am aware we could write this function as a single loop, I am purposefully keeping it as 2 loops to demonstrate the dropping of constant factors.

O(1) means constant - our runtime doesn't scale with our input size - it could always take 10 seconds or a million seconds, but it doesn't change with our input size.
O(n) means linear scaling - 10 seconds for an input length of 1, and 100 seconds for an input length of 10.

EDIT: I have made my email public on my profile if you would prefer to move this conversation there.

**Comment by robconery** [comment]
Yes, you have the wrong version :). I just resent the email - let me know if you don't get it. Also - if you have more to add (though I'm not sure if that's possible) feel free to put in email.

We're saying the same things - you were confusing me with the term "runtime doesn't scale". I read that and think about a scaling a routine/program. I think you're talking about scaling on a graph - if that's the case yes I understand that :). 

If you do leave another issue - do me a favor and ask a few questions first. Let's make sure we understand each other than feel free to lecture all you like :).
