### ISSUE TITLE
Comp Sci, Baby (v0.0.3)

### ISSUE THREAD

**Issue by joe-ratzer** [robconery/feedback#158]
Thanks for writing this book, I'm really enjoying it. 

Here's my initial feedback from reading "Comp Sci, Baby" in v0.0.3:

**Page 40**
**Current**: The good news is your current home only has 6 rooms total...
**Suggestion**: The good news is your current home only has 6 rooms in total...

**Page 41**
**Current**: 
db.query("select \* from sales where product_id = $1", product.id)
product.SalesCount = count;
**Suggestion**:
var count = db.query("select \* from sales where product_id = $1", product.id)
product.SalesCount = count;

**Page 49**
**Current**: She wants offer discounted product bundles...
**Suggestion**: She wants to offer discounted product bundles...

**Page 87**
**Current**: A true expression returns the first argument, A false expression...
**Suggestion**: A true expression returns the first argument, a false expression...

**Page 94**
**Current**: It's important to note that this is not supposed to be a real machine although some have actually made one.
**Suggestion**: It's important to note that this is not supposed to be a real machine although some have actually been made.

**Page 95**
**Current**: Correspondingly, the speed of the of the tape moving through the machine doesn't effect the power of the machine...
**Suggestion**: Correspondingly, the speed of the tape moving through the machine doesn't affect the power of the machine...

**Page 107**
**Current**: ...which meant that Turing Machine's could be built with...
**Suggestion**: ...which meant that Turing Machines could be built with...

**Page 122**
**Current**: As I mention in very beginning...
**Suggestion**: As I mention in the very beginning...

**Comment by robconery** [comment]
All of this has been tweaked/overhauled. Thank you!

**Comment by joe-ratzer** [comment]
Hello Rob,
not sure what happened, but I can see the following haven't been updated in the latest PDF (in imposter_1_0.zip):

**Page 107 (now page 174)**
**Current**: ...which meant that Turing Machine's could be built with...
**Suggestion**: ...which meant that Turing Machines could be built with...

**Page 122 (now page 194)**
**Current**: As I mention in very beginning...
**Suggestion**: As I mention in the very beginning...
