### ISSUE TITLE
Lambda Calculus Reduction incorrect

### ISSUE THREAD

**Issue by adamipc** [robconery/feedback#159]
`\x.(\y.y)) x` does not reduce to x (top of page 85 in version 0.0.3)

It reduces to the identity function `\y.y` but with the x from the outside dropped.

**Comment by adamipc** [comment]
I guess maybe you mean: `\x.((\y.y) x)`? It's not very clear in the book.

**Comment by adamipc** [comment]
Looking at the source of the next example: https://medium.com/@ayanonagon/the-y-combinator-no-not-that-one-7268d8d9c46#.pmlfzrh9d

You see that they never reduce the original term `λy.(λx. x) y` on its own. So I think the confusion comes from your trying to break the example up into smaller chunks and leaving out the context of the next example which is required for it to make sense.

**Comment by adamipc** [comment]
I realize that this isn't technically a bug, but I'm trying to find a way of maybe improving it so that it isn't as confusing. An obvious improvement might be `(\x.(\y.y) x)` to make it not read like `(\x.(\y.y)) x` but that doesn't really match the style for the rest of the chapter.

I think maybe the improvement could be in the subsequent paragraph that explains the reduction. It says "If we apply `x` to `\y.y`" but maybe it would be better to show the reduction of: `\y.y x -> y [y:=x] -> x` leaves `\x.x` since this is building on the previous example so using the same form of reduction makes sense to show the similarities.

I'm going to close the issue since its not _really_ a bug in the text, and you can make changes if you feel it would be useful.

**Comment by robconery** [comment]
Thanks I've been meaning to dig into this more - it's so funny as I've used online reduction tools to confirm and one said it was valid while the other says it wasn't. I have the problem in the hands of two friends who are good at this stuff but I think I'm going to take Gary Bernhardt out to dinner to see what he thinks.

I'm pretty sure there's an error there but I need to understand why  :). Reopening this for now - good catch and thanks!

**Comment by robconery** [comment]
OK I redid things (I think) - I'll be dropping an update in a day or so and would love your thoughts.

**Comment by robconery** [comment]
I think we're good on this - closing!
