### ISSUE TITLE
Cover GRASP?

### ISSUE THREAD

**Issue by mvelosop** [robconery/feedback#162]
Hi Rob,

Great book, we non CS needed it badly, thanks.

Lots of people know or have heard about SOLID and that's good but defining a responsibility has always been hard, not only in the OOP realm.

There's a great guide (IMHO) for that known as GRASP ([https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)]) I have rarely seen it mentioned, even though SOLID and GRASP should both go together.

There's an excellent presentation here: [www.cs.cmu.edu/~aldrich/214/slides/design-grasp.pdf].

So, my suggestion is to expand the "S" topic with GRASP.

I particularly like the presentation, and even though it's copyrighted, well you could at least include the link (it's public after all), and there's holly Wikipedia also ;-)

Best,

**Comment by robconery** [comment]
The title of the issue here is confusing so I changed it (I cover SRP). I'm not entirely sure of the benefit - to be honest I'm pretty happy with the _basic_ principles that are already in there. If I throw in more it tends to confuse. GRASP seems more like a marketing/repackaging gimmick than anything.

**Comment by mvelosop** [comment]
You are right, the title was confusing, much better now.

I think the included sample for RSP is fine, but its quite basic, as it has to be, to make it easy to grasp the concept (no pun intended).

However, as you rightly state in "This sounds simple, but it's actually a little tricky to grasp", the concept is not clear for more complex real-life situations, and there's where I think GRASP helps, as it gives some concrete criteria for assigning responsibilities.

I think it just details the S in SOLID, does not compete with it.

It's Ok keeping it basic, I just think it might help knowing GRASP exists and perhaps a link would suffice.

And if it's Ok to you adding links, i suggest the presentation (www.cs.cmu.edu/~aldrich/214/slides/design-grasp.pdf) it's excellent.

Best,
