### ISSUE TITLE
Databases (v0.0.3)

### ISSUE THREAD

**Issue by joe-ratzer** [robconery/feedback#163]
I'm still enjoying the book, thanks.

Here's my initial feedback from reading "Databases" in v0.0.3:

**Page 186**
**Current**: ...would be way to slow for what they need...
**Suggestion**: ...would be way too slow for what they need...

**Page 187**
**Current**: The net result of this will our customer's email address sprinkled throughout the database.
**Suggestion**: The net result of this will mean our customer's email address is sprinkled throughout the database.

**Page 199**
**Current**: But you can still add more than three dimensions if you want, which is really weird.
**Suggestion**: Remove the line as the point was raised in the previous sentence

**Page 201** 
**Current**: You can find the code for the examples below up at Github.
**Suggestion**: You can find the code for the examples below at Github.

**Page 205**
**Current**: ...chopping the end off of string values that are too long...
**Suggestion**: chopping the end off string values that are too long...

**Page 206**
**Current**: We'll also add a statement right before hand so that the table gets dropped in case
it exists...
**Suggestion**: We'll also add a statement right beforehand so that the table gets dropped in case
it exists...

**Page 207**
**Current**: ...we'll ask for the id column back so we can verify I our insert is working...
**Suggestion**: ...we'll ask for the id column back so we can verify if our insert is working..

**Page 209**
**Current**: OK, as our final exercise here let's let our banned_users back in...
**Suggestion**: OK, as our final exercise here let's put back our banned_users...

**Page 215**
**Current**: I mean we would never write SQL like this because know better!
**Suggestion**: I mean we would never write SQL like this because we know better!

**Page 222**
**Current**: When writing queries with joins, the from table is always to the "left" of the join
whatever table you're joining to is to the right.
**Suggestion**: When writing queries with joins, the from table is always to the "left" of the join; whatever table you're joining to is to the right.

**Page 225**
**Current**: That's kind of a pain but it's really important, otherwise your query gets confused.
**Suggestion**: That's kind of a pain but it's really important, otherwise your database gets confused.

**Page 228**
**Current**: You can find the code for the examples below up at Github.
**Suggestion**: You can find the code for the examples below at Github.

**Page 232**
**Current**: If you limit your result set above to 10 queries and fix the top 2, you'll be good to go.
**Suggestion**: If you limit your result set above to 10 queries and fix the top 2, you've probably fixed enough to see a real improvement.

**Page 236**
**Current**: In our case here, it turns out that query 2 is run often because displaying scores >
100 is a business requirement.
**Suggestion**: It's worth pointing out that putting such business logic in the database can require careful management as it's easily forgotten. Moreover, if the 100 figure is configurable in the application this solution wouldn't work.

**Page 257**
**Current**: Processing gigantic data dumps is a obviously the main selling point of using
MapReduce...
**Suggestion**: Processing gigantic data dumps is obviously the main selling point of using
MapReduce...

**General**
I would like to see at least a reference to Edgar F. Codd, to aid further reading on relational databases.

**Comment by robconery** [comment]
Thanks - fixed up. Cheers!
