### ISSUE TITLE
Programming Languages (v0.0.3)

### ISSUE THREAD

**Issue by joe-ratzer** [robconery/feedback#164]
Another enjoyable chapter, thank you.

Here's my initial feedback from reading "Programming Languages" in v0.0.3:

**Page 259**
**Current**: ...every good builder has an even better tool set to draw from...
**Suggestion**: ...every good builder has an even better toolset to draw from...

**Page 260**
**Current**: Over time, good programming language amass users - and that's where things
get interesting.
**Suggestion**: Over time, good programming languages amass users - and that's where things
get interesting.

**Page 267**
**Current**: There are more issues that I'm sure your aware of...
**Suggestion**: There are more issues that I'm sure you're aware of...

**Page 273**
**Current**: I mean the ones that have cross through my veil of experience.
**Suggestion**: I mean the ones that have crossed through my veil of experience.

**Page 282**
**Current**: Because the stack is always faster.
**Suggestion**: I think this is an oversimplification. For example, if everything was on the stack then code certainly wouldn't be faster.

**Page 282**
**Current**: It can also be buggy, which is a pain.
**Suggestion**: I would remove this line, or qualify it, because I believe GC decreases the likelihood of bugs.

**Page 283**
**Current**: Are subject to boxing/unboxing (moving from stack to heap, or value type to
reference type) which Could Be Bad.
**Suggestion**: Are subject to boxing/unboxing (moving from stack to heap, or value type to
reference type) which could be slow.

**Page 294**
**Current**: ...like IDEs in general, you'll likely find support for you choice with a JetBrains IDE.
**Suggestion**: ...like IDEs in general, you'll likely find support for your choice with a JetBrains IDE.

**Page 309**
**Current**: ...the code on coder!
**Suggestion**: ...then code on coder!

**Comment by robconery** [comment]
Thanks! Fixed!
