### ISSUE TITLE
Fix Jekyll script post automation chapter

### ISSUE THREAD

**Issue by OscarRobertRodriguez** [robconery/feedback#168]
Chapter about Jekyll script for post automation needs work. I'm someone who's never messed with scripts and I was lost. You leave out a lot of information and I feel like you jump around too much without breaking it down step by step. I want to see from beginning to end how you get the script to work not just what all the terms mean. You say to use oh my zsh but then you stop using it on the next chapter without reference or the usefulness of the program.

**Comment by robconery** [comment]
I've removed this chapter entirely. Thanks for the report - you're right it needed some work.
