### ISSUE TITLE
Suggestion: Interesting topics

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#17]
I'm sure you'll get loads of suggestions for things that you could have written about, and I'll be honest, I've spent about 15 mins skimming the book. It looks REALLY good and I'm excited about giving it a proper read.  I did CompSci about 20 years ago, and I'm hoping it will be a refresher and re-primer of how this stuff works in the modern day.

Two things that I've found REALLY useful as a programmer are:
1. understanding how processors work and;
2. how static analysis can help me write better code.
## How processors work

A primer on this would be a great topic for the book. Perhaps this is covered somewhere but I can't see it. The section on how a compiler works is pretty good, but I kinda feel like unless you understand what the target is - what you're trying to get the compiler to spit out and WHY - then talking about compilers is pretty tricky.

The chapter starts by saying that a compiler "simply brings different things together and makes them one thing". This isn't always true, depending on how you're linking. In fact, linking isn't covered...oh my goodness I'm already off down a rabbit hole.

(Opinion:) I'd define a compiler as a tool for translating high-level language code into machine-level code that a processor can understand. Sometimes via an intermediate language. 

You then say that a compiler "generates something that the runtime engine can execute" without explaining what a runtime engine is. I kinda feel that without an understanding of the target/object code, we shouldn't start talking about compiling and interpretation. You also mention "Native code" without explaining what that is.

There is SO much you could explore here and I don't blame you for summarising. But in general understanding that hierarchy of languages and why you need to get from a high level language to a lower level language might be helpful.  Small snippets of assembler/byte code, or a beautiful hand-drawn diagram may really help.

I'm also just gonna mention that there's no discussion of strong/weak typing. Perhaps that's something you deliberately avoided (I don't blame you).
## Static analysis

OK, OK, I'm a weirdo. I used to work in safety critical software engineering and I would rather write Ada than JavaScript. Elm really appeals because the compiler, apparently, tells you you've done stuff wrong. I use an IDE that tells me when variables are unused and shit like that.

The point is, there is an area of computing that very few people know about that is actually really helpful for writing better code.  Static analysis tells you when you have unused variables, loop invariants, mis-matched types, even when you go outside array bounds (and how many security holes are caused by array bounds!?!?)

I just wondered if this was a topic worth exploring. So many beginner languages - especially the languages of the web (JS, PHP, etc), in my opinion promote terrible coding practices. They are weakly typed, make assumptions about what you want to do, let you do pretty much anything without question.  I'd love to see an critique of some of this, some info on static analysis and how compilers and static analysis tools in certain languages can detect certain things and help you remove them, eliminating basic errors.

Perhaps this is beyond the scope of the book, and I acknowledge that this is highly opinionated. But perhaps you can add it to a wish list or something.

Thanks, brilliant work. After I've had a read I'm sure I'll be recommending it to many.

**Comment by robconery** [comment]
Before I respond in full - would you mind splitting Static Analysis into a separate issue? It'll _really help_ in terms of keeping track of the conversations. I'll respond to the compiler question here.

First: given the scope of the book (which is rather aggressive) - yes, I need to stop at some point or else I'll never finish the book. Looks like you've come right against those edges :). But I'm happy to further round out some things.

> The chapter starts by saying that a compiler "simply brings different things together and makes them one thing". This isn't always true, depending on how you're linking.

The definition of the word _compile_ means to produce something new by assembling things from different sources. I don't mean to get too literal on you here, but compilation reduces code into some form of library or executable. Can you expand on the exception you see?

>  I'd define a compiler as a tool for translating high-level language code into machine-level code that a processor can understand.

I think you and I agree on this one, but translation is only the final step and actually the least interesting. Lexing and optimization are far more intense - if I was to define a compiler in this way, it would be underserving it really.

> You then say that a compiler "generates something that the runtime engine can execute" without explaining what a runtime engine is. 

Yeah - I can move the Runtimes chapter first or (what I would prefer) I can add a "toss" saying it will be explained in due course. Also: I do assume (as mentioned in the intro) some experience here. So I'm wondering where the line is between understanding what a runtime is vs. needing an explanation? Thoughts?

Good point RE Native Code - I'll expand on that.

> But in general understanding that hierarchy of languages and why you need to get from a high level language to a lower level language might be helpful.

I don't know if I follow the _need_ part on this. Why do you think this is important? I'm happy to add - I'm just not sure what you mean :).

**Comment by rosswintle** [comment]
Amazing that you're taking feedback this way. Thank you. I'm totally happy if you change **nothing** by the way. It's amazing that you wrote this thing and I'll probably gift it to some people.

> Can you expand on the exception you see?

Hah - how to tie yourself (that is, myself!) in knots. I do understand your definition and see why you have used it. My exception is an executable that has dynamically linked shared libraries. In my view such an executable is not "one thing". But actually, your definition doesn't say that the compiled "one thing" is a **complete** thing. So you're good.

I guess we're left with the question: do you want to cover linking as part of the compilation process? Or is that too far down the rabbit hole?

> translation is only the final step and actually the least interesting. Lexing and optimization are far more intense

I totally agree, and studying compiler construction gave me a real yearning to study linguistics!

I guess my point was that there's no explanation of "why" we need to compile and interpret high-level languages. Chad, in his forword, talks about the process of understanding computers from the bottom up:

> Everything starts with this simple foundation [of parts that are pretty simple] and grows as simple blocks on top

Understanding what's going on underneath can/may give you an appreciation of what's going on at a higher level.

> I'm wondering where the line is between understanding what a runtime is vs. needing an explanation? Thoughts?

That's a balance you're trying to strike as author of a book that you rightly acknowledge as potentially bunny-chasing. I don't envy you! Perhaps you should leave it for now and see if anyone else picks up on it.

> I don't know if I follow the need part on this.

See above - compilation and interpretation takes you from high-level languages to low-level languages. Why can't we just build (physical) machines that interpret Java? Why is this compilation necessary? We NEED to get from human-readable code into machine-readable code. I guess that's why I'm arguing that a discussion of what the machine is might help.

**Comment by robconery** [comment]
Thanks again for all of this - I think I'll have a second edition, maybe - I've marked this for v2 (if that's the right name) ... thanks again.

**Comment by robconery** [comment]
Kicking this to a later volume. Thanks again!
