### ISSUE TITLE
Suggestion: Text that can be removed

### ISSUE THREAD

**Issue by thomashuysmans** [robconery/feedback#170]
In the chapter Big O there is some text that I think can be removed. On page 60 at the top is written "you decide that you'll store these results in a separate table that you can populate on a nightly basis (because you now understand how cron works)."

The text "(because you now understand how cron works)" made sense in the previous versions because of the Linux chapters where you did explain what cron was and how it works. This is just a suggestion.

I found this in version 0.0.4

**Comment by robconery** [comment]
Thanks - removed!
