### ISSUE TITLE
A handful of typos in the '05' PDF

### ISSUE THREAD

**Issue by drbyte** [robconery/feedback#171]
Here are a few dozen minor edits to fix, as discovered in imposter_05.pdf

Instead of opening multiple Issues, I've simply stuck checkboxes before each, so you can indicate which ones you've addressed, at your convenience.

I elected to go sequentially, but if you want to rearrange, you can drag them up and down to regroup them.
- [x]  page 13: missing space in "obsessed `withRussell's` Paradox"
- [x] page 13: This `later` point ... Did you mean to say `latter`?
- [x] page 24: missing space in: "nagging feeling that I just don't `belonghere.`"
- [x] page 27: (missing a word, such as "with") in:  "In fact, most people seem to `leave university very little` actual ability and ..."
- [x] page 34: Did you mean to italicize "be" in "... should _be_"?  Or did you really mean to italicize _should_ instead?
- [x] page 38: "Packing up my `kids` things" ... "kids" should be "kid's" because it refers to one (Ruby) and reflects ownership.
- [x] page 48: (may be trivial, but) Did you mean to say "small" containers twice (X and Z) in: `Can I optimally fit all of Ruby's things into X small containers, Y medium containers and Z small containers?`
- [x] page 53: "problems" vs just "problem" in: `variation of another NP-Hard problems called Knapsack.`
- [x] page 58: `than` should be `then` in: `If we had a nondeterministic algorithm than every problem...`
- [x] page 60: missing a word (maybe replace `that` with `we`) in: `in the short time that have to play`
- [x] page 76: `in` is this an extra word? or should it be `is`?  :  `to find the actual value in within the clustered primary key index.`
- [x] page 76: why did the footer disappear on this page?
- [x] page 97: point # 1 has the `1.` twice: `1. 1. The basics of Lambda Calculus`
- [x] page 102: the 2nd bullet is indented oddly: `• You can bind or substitute functions using a λ binding`
- [x] page 145: `cornerstone's` should be `cornerstones`, without the apostrophe
- [x] page 150: `of the` is duplicated in: `the speed of the of the tape moving through the machine`
- [x] page 150: `effect` should be `affect` in: `none of these effect what problems are solvable`
- [x] page 154: this time `affect` should be `effect` in: `This idea had quite a profound affect,`
- [x] page 156: `simple` should be `simply` in: `Turing simple decided to assume it existed.`
- [x] page 156: `it's` should be `its` in: `as well as it's tape.`
- [x] page 158: `want's` should be `wants` in: `Maybe your boss want's you`
- [x] page 164: missing a space in `programthat`
- [x] page 176: missing a space in "accepts `orrejects` something"
- [x] page 200: no footer on this page?
- [x] page 208: no footer on this page?
- [x] page 215: `it's` should be `its` in: `single node knows nothing about it's children`
- [x] page 218: should it be "`a` graph"? in: `binary search tree is graph`
- [x] page 219: `takes` should maybe be `take` in: `as to which node will ascend and takes its place`
- [x] page 238: no footer on this page?
- [x] page 239: no footer on this page?
- [x] page 242 says the following, but it's not clear what `this book` refers to. Did you mean to include a name and link to a book?
  
  > Know your algorithms. Pick any of these here.
  > So I did just that. I’ll admit, getting through `this book` was tough and I skimmed quite a few sections. But if you want to know more about Algorithms we’re about to discuss, this is a great start!
- [x] page 247: extra word `example` in: "but the marbles aren’t `example` sorted yet."
- [x] page 258: _twice in first paragraph `it's complexity` should be `its complexity`
- [x] page 281: `you` should be `your` in: "quicksort or merge sort are `you` best bets,"
- [x] page 290: missing space before `with` in: `Problem)when`
- [x] page 290: `us` should be `use` in: `You don’t need to us x plus some other`
- [x] page 301: missing "the"? ... in: `To see this, let’s add a counter to function:`
- [x] page 303: `thens` should be `then`in: `happy with our answer and thens asks us:`
- [x] page 304: `it's` should be `its` in: `anything else to use it’s value.`
- [x] page 327: `then` should be `than` in: "Rather `then` spend many words on it"
- [x] page 327: in: 'it’s a “delta”, which `means indicates` a difference.' ... maybe remove one of `means` or `indicates`?
- [x] page 345: `no` should be `not` in: "it is `no` the most efficient algorithm."
- [x] page 346: no footer on this page?
- [x] page 347: no footer on this page?
- [x] page 359: `it's` should be `its` in: `without losing it’s clarity?`
- [x] page 365: `then` should be `than` in: `rather then change`
- [x] page 367: "`basing` and `based`" in the same sentence: `and basing the meaning of those words based on emphasis.`  Maybe remove the 2nd one? 
- [x] page 376: Given that it's already happened, perhaps it may be good to change "is introducing" to just "introduced" in `JavaScript (or ECMASript 2015) is introducing the let keyword`
- [x] page 387: `effecting` should be `affecting` in: `appears to be effecting progress`
- [x] page 388: `here` should be `hear` in: `You'll often here JVM and JRE`
- [x] page 396: should `comes` be `comes up`? in: `every time the subject comes`
- [x] page 396: no footer on this page?

**Comment by drbyte** [comment]
- [ ] page 145: `cornerstone's` should be `cornerstones`, without the apostrophe
- [ ] page 150: `of the` is duplicated in: `the speed of the of the tape moving through the machine`
- [ ] page 150: `effect` should be `affect` in: `none of these effect what problems are solvable`
- [ ] page 154: this time `affect` should be `effect` in: `This idea had quite a profound affect,`
- [ ] page 156: `simple` should be `simply` in: `Turing simple decided to assume it existed.`
- [ ] page 156: `it's` should be `its` in: `as well as it's tape.`
- [ ] page 158: `want's` should be `wants` in: `Maybe your boss want's you`
- [ ] page 164: missing a space in `programthat`
- [ ] page 176: missing a space in "accepts `orrejects` something"
- [ ] page 200: no footer on this page?
- [ ] page 208: no footer on this page?
- [ ] page 215: `it's` should be `its` in: `single node knows nothing about it's children`
- [ ] page 218: should it be "`a` graph"? in: `binary search tree is graph`
- [ ] page 219: `takes` should maybe be `take` in: `as to which node will ascend and takes its place`
- [ ] page 238: no footer on this page?
- [ ] page 239: no footer on this page?

- [ ] page 242 says the following, but it's not clear what `this book` refers to. Did you mean to include a name and link to a book?

  > Know your algorithms. Pick any of these here.
So I did just that. I’ll admit, getting through `this book` was tough and I skimmed quite a few sections. But if you want to know more about Algorithms we’re about to discuss, this is a great start!

- [ ] page 247: extra word `example` in: "but the marbles aren’t `example` sorted yet."
- [ ] page 258: _twice in first paragraph `it's complexity` should be `its complexity`
- [ ] page 281: `you` should be `your` in: "quicksort or merge sort are `you` best bets,"
- [ ] page 290: missing space before `with` in: `Problem)when`
- [ ] page 290: `us` should be `use` in: `You don’t need to us x plus some other`
- [ ] page 301: missing "the"? ... in: `To see this, let’s add a counter to function:`
- [ ] page 303: `thens` should be `then`in: `happy with our answer and thens asks us:`
- [ ] page 304: `it's` should be `its` in: `anything else to use it’s value.`

**Comment by drbyte** [comment]
okay, time for sleep while my brain digests all this CS stuff!  
(BTW: thanks for pulling all this into laymans terms. I"m getting some great refreshers, and lots of stuff I should already know. Cheers!)

**Comment by robconery** [comment]
Phew! That was RAD! Thank you SO MUCH for all the time you spent on this AND for the amazingly lovely issue! Love you!
