### ISSUE TITLE
Found some issues in the '05' epub

### ISSUE THREAD

**Issue by thecodejunkie** [robconery/feedback#172]
Uploaded the '05' epub to Google Books and noticed a couple of things - mostly related to work-breaking

Page 15 (not sure if this is intentional or not?)

![image](https://cloud.githubusercontent.com/assets/50543/19635397/62300e34-99c2-11e6-889b-3547289d2c61.png)

Page 17

![image](https://cloud.githubusercontent.com/assets/50543/19635380/2eaa04ac-99c2-11e6-9db2-49f2f279e998.png)

Page 52 (not sure if this is intentional or not?)

![image](https://cloud.githubusercontent.com/assets/50543/19635420/8586233c-99c2-11e6-9feb-405e6ef50fb5.png)

Page 111 (not sure if this is intentional or not?)

![image](https://cloud.githubusercontent.com/assets/50543/19635450/b272666c-99c2-11e6-8018-b44d3a1ff9a2.png)

Page 164 (not sure if this is intentional or not?)

![image](https://cloud.githubusercontent.com/assets/50543/19635464/d08eff20-99c2-11e6-9bb7-9eee24f50c88.png)

**Comment by robconery** [comment]
I fixed the weird indent thing but... yeah Google is reformatting all of my carefully formatted stuff... nothing I can do about that other than to say "don't load it to Google"

**Comment by robconery** [comment]
This is Google doing a number of things…

1 - completely breaking the fonts/font size/formatting
2 - replacing spaces with tabs in random locations 

Don’t know what I can do in this case.
