### ISSUE TITLE
Unable to Download Drop #5

### ISSUE THREAD

**Issue by sonnythao** [robconery/feedback#173]
Hi Rob,

I, for one, am always excited to see all the updates you've been making to your AWESOME book!  I haven't gotten through it completely, but am enjoying what I've read thus far.  Keep up the great work!

I received Drop # 5's email, but when navigating to the site and clicking the "Download" button, I'm never presented with a download pop-up - the site just sits there with a "Waiting for transactions.sendowl.com" status.  I've not tried the download twice and am down to 1 download remaining and I don't want to try again, for fear of running out my allowed number of downloads.

I'd appreciate any help that can be given.

Thanks,

Sonny

**Comment by robconery** [comment]
Hiya - this isn't feedback so closing. We can take it to email.

**Comment by sonnythao** [comment]
Roger.  Thanks for the prompt reply!  Just emailed you.
