### ISSUE TITLE
Book ends too soon :-)

### ISSUE THREAD

**Issue by CarteriTrellis** [robconery/feedback#177]
In the Kindle edition, you cannot advance the pages past location 7503 of 8xxx.

**Comment by robconery** [comment]
Hmmm. What Kindle do you have? In the emulator I have hear everything works fine. There's also a PDF if the mobi isn't working. At this point my stance with Kindle is pretty much "if it's not working out here's a refund". Kindle is, right now, 90% of my workload and 5% of my sales. I hate to be so cut and dry about it, but it's a pretty difficult ecosystem to deal with from the author's perspective.

**Comment by CarteriTrellis** [comment]
It's a 3rd gen Fire HD. Up until now, I had been reading the PDF version, and I wanted to see what the experience was like on the Kindle, so: no refund necessary here. Thanks!
