### ISSUE TITLE
Citation needed

### ISSUE THREAD

**Issue by CarteriTrellis** [robconery/feedback#178]
You reference the classic work Flatland without citing it. Kindle edition, location 405 of 8xxx. Maybe consider a link, like you used for The Travelling Salesman Problem?

**Comment by robconery** [comment]
Flatland? Help?

**Comment by CarteriTrellis** [comment]
Oh! It's where the apple passing through the 2D space comes from: https://en.wikipedia.org/wiki/Flatland

(Actually, I just went and looked it up: the specific example of an apple comes from Cosmos, where Sagan uses an apple to illustrate the same points made in Flatland - http://blog.world-mysteries.com/science/higher-dimensions/)

**Comment by robconery** [comment]
The Cosmos example was one that I remember as a kid and that I also heard in school. I thought it a familiar analogy so didn't cite it but I suppose I probably should.

**Comment by CarteriTrellis** [comment]
Yeah, I remember watching the TV series when it first aired; I can't say that Cosmos is definitely the source, but it certainly popularized the analogy. Couldn't hurt to reference Cosmos for, uh, geeks of a certain age. :-)
