### ISSUE TITLE
Testing chapter removed?

### ISSUE THREAD

**Issue by HyShai** [robconery/feedback#179]
Was the testing chapter intentionally removed? I really liked it, and there are still references to the chapter in other parts of the book.

**Comment by robconery** [comment]
Weird - no it wasn't... so strange as I was just talking about it today. And... wow it's not in there. This book is getting far too big!

I'll be sure it goes back in.

**Comment by robconery** [comment]
It's back in now, going out tonight/tomorrow.

**Comment by HyShai** [comment]
Thanks. 

You removed the BDD part, right?

Was it because BDD is too hard to explain via the written word?

**Comment by robconery** [comment]
Crap - I forgot to add that part in too. I’ll add it back for the first rev in a few weeks.
