### ISSUE TITLE
Save to dropbox not working on sendowl site

### ISSUE THREAD

**Issue by pierskarsenbarg** [robconery/feedback#180]
Clicked on the link in the latest email, clicked "Download to dropbox".

It then asked me what folder I wanted to save it to. I then told it to save but it threw an error. I've now run out of chances to download the latest version.

**Comment by robconery** [comment]
Hi Piers - this isn't an issue with the book, it's an issue with SendOwl. I reset your counters and, as you can imagine, there's just nothing I can do to troubleshoot what happened between Dropbox and SendOwl. The only the thing I could suggest is to download the book yourself and drop it into Dropbox.

Either way - your counters are reset.

**Comment by pierskarsenbarg** [comment]
Thank you 😄
