### ISSUE TITLE
No TOC?

### ISSUE THREAD

**Issue by fozcodes** [robconery/feedback#181]
Hey Rob,

Just downloaded the 1.0 - it's looking great. There's no Table of Contents though - is that intentional? Maybe you're just waiting to finalize some stuff.

Thanks!

**Comment by robconery** [comment]
There is - it's just not inline :). Another person asked me about this - I guess I'll put it back for the next drop.

**Comment by fozcodes** [comment]
Awesome thanks man! Yeah it's useful with PDF readers to navigate quicky.

Awesome work, love the book!

**Comment by robconery** [comment]
Oh you can still do that - there’s an outline that comes with it; what reader are you using?

**Comment by fozcodes** [comment]
Oh my god, I'm an idiot. I'm using Adobe reader on my phone. 

Learn how to use your tools, Ian!

Maybe a final chapter on how to use PDF software so that you can read books teaching you how to use Linux? 😎

Thanks dude, the outline is actually way better than inline.

**Comment by robconery** [comment]
LOL please - it's my fault for confusing you :). No problem at all - you're not the first to ask about this so I think I'll have to change.
