### ISSUE TITLE
Software Design (PDF in imposter_1_0.zip)

### ISSUE THREAD

**Issue by joe-ratzer** [robconery/feedback#182]
As before, thank you for writing the book!

Here's my initial feedback from reading Software Design from the PDF in imposter_1_0.zip:

**Page 555**
**Current**: A Singleton is a class that only allows one instance of itself. It's is not an easy thing to do correctly...
**Suggestion**: A Singleton is a class that only allows one instance of itself. It's not an easy thing to do correctly...

**Page 559**
**Current**: The problem is that we now have to go implement it for every adapter...
**Suggestion**: The problem is that we now have to go and implement it for every adapter...

**Page 561**
**Current**: It turns out that the some of the drivers we've been using don't implement connection pools...
**Suggestion**: It turns out that some of the drivers we've been using don't implement connection pools...

**Page 569**
**Current**: ...but when it comes to validations there are better ways to do this.
**Suggestion**: Why not choose an example that makes more sense?

**Page 585**
**Current**: I started working in a functional language (Elixir) this last year and I love it. 
**Suggestion**: I started working in a functional language (Elixir) last year and I love it. 

**Page 599**
**Current**: As you build applications using the patterns we learned in the in a
previous chapter...
**Suggestion**: As you build applications using the patterns we have been learning...

**Page 606**
**Current**: YAGNI (You Aint Gonna Need It)...
**Suggestion**: YAGNI (You Ain't Gonna Need It)...

**Page 618**
**Current**: We still have coupling to a the notion of an IDataStore...
**Suggestion**: We still have coupling to the notion of an IDataStore...

**Page 623**
**Current**: As your application grows and becomes more complex, it's becomes easier to find yourself creating circular dependencies.
**Suggestion**: As your application grows and becomes more complex, it becomes easier to find yourself creating circular dependencies.

**Page 639**
**Current**: I know that people like to argue about what they think it is and what think it is not.
**Suggestion**: I know that people like to argue about what they think it is and what they think it is not.

**Page 650**
**Current**: This where we venture into silly land.
**Suggestion**: This is where we venture into silly land

**General**
I think the discussion on IoC should include a mention on why it makes unit testing easier.

**Comment by joe-ratzer** [comment]
By the way, I know this 70 year old man from New York who has never written a line of code in his life - he's never even had a job in IT. However, he's been offered the world's most important programming job, which would test the abilities of the most experienced developer. He has accepted the position but will surely feel like an impostor - do you think your book will be enough?

**Comment by robconery** [comment]
Ugh... just... sigh.

Also: thanks for these. I really, really appreciate you doing this.

**Comment by robconery** [comment]
All set thanks!

**Comment by joe-ratzer** [comment]
No worries, it's good seeing the book come together. That all looks done in the latest version, except YAGNI is still missing an apostrophe. Sorry! :)

And just in case you didn't see it - I added a comment to the old closed issue titled "Comp Sci, Baby (v0.0.3)".

**Comment by robconery** [comment]
Yeah I decided it wasn't a contraction :). Just slang...

**Comment by joe-ratzer** [comment]
Ok, good stuff. :)
