### ISSUE TITLE
Big Machine address is incorrect

### ISSUE THREAD

**Issue by texel** [robconery/feedback#184]
Address is listed as `Big Machine, Inc 111 Jackson, Seattle WA 96714`.

The street is `South Jackson` and the zip should be `98104`.

Normally I wouldn't notice something this pedantic, but the Seattle address with a "96" zip code jumped out at me. I *wish* Pioneer Square was in Hanalei!

**Comment by robconery** [comment]
LOL that's rad - thanks. Where did you see this address?

**Comment by texel** [comment]
It's on page 3 of the PDF in the "Published by:" section.

**Comment by robconery** [comment]
Gah - that's dopey of me! Fixed - thanks.
