### ISSUE TITLE
Von Neumann Machine spelling in ToC and Section Heading

### ISSUE THREAD

**Issue by jbellars** [robconery/feedback#185]
Greetings. While taking a break from updating German resource bundles for applications that are being internationalized, I checked my email to see the update of the handbook. I opened it up and started looking through the ToC only to be horrified that Von Neumann was spelled "Von Nuemann" ... in both the ToC on pg. 5 and in the section heading on pg. 172. 

In the body of the text it is spelled correctly, but please make sure you fix the ToC and section heading before rolling it out to print!

**Comment by robconery** [comment]
Ugh - very sorry about this! Fixed...
