### ISSUE TITLE
ARC usage

### ISSUE THREAD

**Issue by schroederm** [robconery/feedback#186]
In the section about Garbage Collection, you state most developers (from your sources) don't use ARC in their projects. In my experience, no one ever uses Obj-C (or Swift, which uses the same memory management paradigm) without ARC anymore (expect for legacy projects maybe). The hassle and hidden bugs introduced by managing memory by hand would simply be too expensive timewise, by today's standards.

**Comment by robconery** [comment]
You're very correct - this is completely my mistake. I went off old information that I evidently misunderstood from a friend of mine who's a iOS dev. What he meant to say what "people should learn to use Objective-C without ARC" so they understand memory management at a lower level. That came across as "no one uses ARC", which is dumb. This has been fixed.
