### ISSUE TITLE
Essential Unix Tools (PDF in imposter_1_0_1.zip)

### ISSUE THREAD

**Issue by joe-ratzer** [robconery/feedback#189]
As usual, thank you for writing the book...

Here's my initial feedback from reading "Essential Unix Tools" from the PDF in imposter_1_0_1.zip:

**Page 687**
**Current**: ...if you’re looking for something a bit more friendly than I might recommend having a look at Z Shell.
**Suggestion:** ...if you’re looking for something a bit more friendly then I might recommend having a look at Z Shell.

**Page 684 & 686**
**Current:** Powershell
**Suggestion:** PowerShell

**Page 689**
**Current:** Google it if you like, but the actual meaning of it doesn't matter.
**Suggestion:** Remove the sentence

**Page 696**
**Current:** The -p flag tells mkdir to create the entire structure if its not already there.
**Suggestion:** The -p flag tells mkdir to create the entire structure if it's not already there.

**Page 713**
**Current:** We need to check of this directory exists before we do anything.
**Suggestion:** We need to check if this directory exists before we do anything.

**Page 714**
**Current:** If I put then on a new line the semicolon isn’t needed.
**Suggestion:** If I put them on a new line the semicolon isn’t needed.

**Page 716**
**Current:** To unconfuse the shell we can use quoting...
**Suggestion:** To assist the shell we can use quoting...

**Page 722**
**Current:** When you execute a shell script, we did above, it’s given it’s own process.
**Suggestion:** When you execute a shell script, as we did above, it’s given its own process. [Two changes]

**Page 719**
**Current:** The good news I can do this by turning it into a function...
**Suggestion:** The good news is I can do this by turning it into a function...

**Page 724**
**Current:** Have at it.
**Suggestion:** Have a play at it.

**Page 729**
**Current:** ...which we also discussed last section...
**Suggestion:** ...which we also discussed in the last section...

**Page 739**
**Current:** With Grunt, it's a Gruntfile; with Rake its a Rakefile.
**Suggestion:** With Grunt, it's a Gruntfile; with Rake it's a Rakefile.

**Comment by jbellars** [comment]
All of these sound good, except the Page 724 suggestion. I've never heard a native English speaker use the suggested expression, "Have a play at it." If the colloquialism, "Have at it" is confusing, perhaps simply "Play with it." or "Experiment." would suffice..?

**Comment by bobosola** [comment]
Page 724 "have at it". This perfectly acceptable in UK English at least. It's generally used in a light jocular manner which I suspect is the meaning Rob intended. A bit like "knock yourself out" combined with "give it your best shot".

**Comment by robconery** [comment]
Thanks so much! This is great :) fixes in place...
