### ISSUE TITLE
Section doesn't logically follow

### ISSUE THREAD

**Issue by alj1s** [robconery/feedback#19]
At the top of page 42 it states, "As it turns out, this is the /bin directory..."

This suggest some previous discussion of a directory, but the previous section creates a new directory, secret and covers the difference between group and owner privileges.

So I don't see where this follows.

**Comment by robconery** [comment]
Thanks - that was a late addition and I think my little note there broke up the flow. I've massaged it to read better...

**Comment by alj1s** [comment]
Great. Loving it so far!
