### ISSUE TITLE
Cycle in graphs

### ISSUE THREAD

**Issue by bobosola** [robconery/feedback#190]
On pages 245 & 249 you demonstrate a cycle in a graph with the comment _this path is a cycle_. But it looks to me (from my non-CS educated POV) that the opposed directional arrows of the bottom left vertex actually make it _non_-cyclic? In other words, you can’t traverse the highlighted path from any vertex in the path and end up at the starting vertex?

It’s entirely possible that I have misunderstood the meaning of a cycle here. So could please clarify why it is in fact a cycle despite the directional constraints, or maybe correct it if it isn’t? Fabulous book by the way - I’m enjoying the occasional offsite links like the mind-blowing Jim Weirich keynote almost as as much as the content. Great stuff!

**Comment by chrisseaton** [comment]
Yes, there is no cycle as illustrated on his page.

The grey line shows a cycle moving along an orange line that is directed the other way.

**Comment by robconery** [comment]
Yeah this is a goofy bug - thanks for reporting... fixed for next rev.
