### ISSUE TITLE
Polynomial exponents not rendered properly

### ISSUE THREAD

**Issue by rjshade** [robconery/feedback#191]
The blockquote on page 46 describing polynomials doesn't have the exponents rendered properly:

"An example of a polynomial of a single variable x is x2 − 4x + 7. An example in three variables is x3 + 2xyz2 −yz+1."

x2 should be x^2 for example.

**Comment by robconery** [comment]
The PDF has numerous formatting issues which I'll be addressing in the next drop, coming in about 2 days time. Thanks for reporting!
