### ISSUE TITLE
Software Design (PDF in imposter_1_0_1.zip)

### ISSUE THREAD

**Issue by joe-ratzer** [robconery/feedback#197]
Hello Rob,

Here's some feedback from reading _Software Design_ from the PDF in imposter_1_0_1.zip:

**Page 545
Current:**
...a set of blue prints...
**Suggestion:**
...a set of blueprints...

**Page 546**
**Current:**
John Vlissedes
**Suggestion:**
John Vlissides

**Page 550
Current:**
...decide whether anAdministrator should be returned...
**Suggestion:**
...decide whether an Administrator should be returned...

**Page 552
Current:**
overly complex objects are ripe for bugs...
**Suggestion:**
Overly complex objects are ripe for bugs...

**Page 558
Current:**
Adapter Pattern
**Suggestion:**
Isn't your example just an abstraction? I thought the adapter pattern was for working with existing code...

**Page 572
Current:**
Speaking of, let's create our User class...
**Suggestion:**
Speaking of which, let's create our User class...

**Page 588
Current:**
Functional languages are a natural for distributed programming...
**Suggestion:**
Functional languages are a natural fit for distributed programming...

**Page 603
Current:**
...devote the rest of the chapter to that meaning.
**Suggestion:**
...devote the rest of this section to that meaning.

**Page 617
Current:**
...our Membership class cannot be used unless a DBinstance is passed in.
**Suggestion:**
...our Membership class cannot be used unless a DB instance is passed in.

**Page 624
Current:**
I'd like to leave this chapter with a great quote from my friend Gary Bernhardt...
**Suggestion:**
I'd like to leave this section with a great quote from my friend Gary Bernhardt...

**Page 630
Current:**
We could go and fix the bug directly inside of node_modules, but that would violate Open/Closed!
**Suggestion:**
Would it be better to highlight that the principle allows behavior to be added without changing existing code, rather than discuss bugs?

**Page 679
Current:**
...the start of this chapter compared with the code from the last chapter on TDD.
**Suggestion:**
...the start of this section compared with the code from the last section on TDD.

Thanks,
Joe

**Comment by robconery** [comment]
Cheers - thanks :). RE the Adapter - it simply adapts one API to another, so yes your definition fits but it's a bit simpler than that. The `GroovyPostgresAdapater` is allowing our `GroovyQuery` to use the postgres driver without implementing it directly.
