### ISSUE TITLE
The link to this github page from the website is a link to the way back machine

### ISSUE THREAD

**Issue by phaselden** [robconery/feedback#198]
Hi, I suspect this is not intentional...

The link on this page: https://bigmachine.io/products/the-imposters-handbook/
is to:
https://web.archive.org/web/20160828140729/https://github.com/imposters-handbook/feedback/issues

**Comment by robconery** [comment]
Wow... WTH? That's... really strange. I mean... *really* strange. I have no idea why that would be there... hmmm. Fixed and thanks :).
