### ISSUE TITLE
The Kindle version does not include a table of contents

### ISSUE THREAD

**Issue by phaselden** [robconery/feedback#199]
My copy was purchased and downloaded on the 1 Dec, so assume that it is fairly up to date.

**Comment by robconery** [comment]
That's... odd. Even in the front of the book? Is there an outline somewhere? Which Kindle are you using?

**Comment by phaselden** [comment]
Hi Rob,

Just checked again. My original comment was for version 1 (or 1.1) I think, 

The TOC showed up for 1.2 and I just loaded 1.3 and it has the TOC too. However, its formatting can be a little wonky in both these versions. For example:
![screenshot_2017_03_17t09_26_05 1100](https://cloud.githubusercontent.com/assets/216304/24021294/6c5277f0-0af4-11e7-91a6-40aaeb40716d.png)

I'm using a Voyage.

**Comment by robconery** [comment]
Yeah there's something weird with Softcover and the layout for Ch. 3 in the TOC. I'll see if I can fix that for next rev...

**Comment by phaselden** [comment]
Rather than create a separate ticket...

I loaded the epub onto my iPad Air 2. At Chapter 5 things start going wonky. The TOC reflects this. For example, the first subsection in Ch 5 is "5.5.1" then ".1" (in the TOC), etc etc. 
From this point on, the first 2nd level subheading in each chapter in the TOC has a bullet point before it. ie 6.1, 7.1, 8.1, etc.

Maybe there's a line ending issue?

**Comment by robconery** [comment]
Cheers thanks Phil. I have a suspicion that it's the way Softcover is reading the heading tags. I think I have a plan - I'll get another rev out in 2 weeks or so.
