### ISSUE TITLE
feedback page 153: Global and local dependencies

### ISSUE THREAD

**Issue by luddd3** [robconery/feedback#2]
Hi,

Regarding global and local dependencies in the section Binaries on page 153.

When I have spoken with people new to Node.js they have often initially been confused about local and global dependencies. I think it maybe would be worth to explain the difference to beginners.

**Comment by robconery** [comment]
Good point - I don't have a page reference here since the ebooks can be different sizes depending on fonts and OS stuff - which chapter/passage? And thanks :).

**Comment by luddd3** [comment]
Sorry, I got the page numbers when reading it on gumroad online.

This issue (in lack of a better word) was found at:
Linux -> Task: Replacing Grunt With Make -> Step 3: Define The Variables -> Binaries

Do you have any preference for how to name the issues? I have some more things that I have found and would you like separate issues for them as well?

Thank you!

**Comment by robconery** [comment]
No preference - this is fine. I didn't know you could read online! How funny :). Thanks for this...

**Comment by robconery** [comment]
Lovely - found it and added a blurb. Thanks!
