### ISSUE TITLE
1.3.3 The sed Command -- explanation needs [[:alnum:]] regex fixed to include caret

### ISSUE THREAD

**Issue by derick** [robconery/feedback#204]
The explanation currently reads:

> We’re using a regular expression `[[:alnum:]]`, which means "anything not alpha-numeric" (`:alnum:` is short for alpha-numeric if you haven’t guessed that). The full expression says search globally for anything not alpha-numeric and replace it with a -: `s/[[:alnum:]]/-/g`.

But I think this needs to have the caret added into the first and third of those code snippets, like it does in the actual full code examples.  Without the caret, your regular expression isn't actually doing a NOT.

**Comment by robconery** [comment]
Help me understand what code you're talking about? I'm looking over the Jekyll post bits here and `alnum`  has a caret as it should (yes, you're correct on that).

**Comment by ghost** [comment]
Refer to section 15.3.3 - "The sed command", which contains the text @derick quoted:

![alnum](https://cloud.githubusercontent.com/assets/27807901/25224167/aedb08a2-2611-11e7-8015-f63f67cee662.jpg)

Note the `[[:alnum:]]` (and the same within `s/[[:alnum:]]/-/g`), whereas elsewhere you have used `[^[:alnum:]]`.

i.e. your explanation states that `[[:alnum:]]` means "anything *not* alpha-numeric" but it actually means "anything alpha-numeric".

**Comment by robconery** [comment]
Weird; I see the caret here in text... wonder if it's getting stripped in the conversion. Sigh.

**Comment by robconery** [comment]
Yep - I fixed the formatting problem for the next drop. Thanks for letting me know...
