### ISSUE TITLE
Mismatched parenthesis

### ISSUE THREAD

**Issue by Perrow** [robconery/feedback#206]
Last paragraph of Big-O (imposter_1_2.pdf).

"O(logn) (and O(nlogn) increase...".

Also, there should really be a line in the graph for O(logn), though at the current Y axis scaling it might be hard to show the "curve" of that line.

**Comment by robconery** [comment]
The PDF has severe formatting issues which I'll be fixing in the next release. Sorry about the trouble and thanks for reporting :).
