### ISSUE TITLE
PDF 1.3 - Formatting issues

### ISSUE THREAD

**Issue by phaselden** [robconery/feedback#207]
I realise you mentioned TOC issues in your email, but thought I would pass on some observations in case these are different:
* Each major section on a new page. 
* The "C" in Chapter is sometimes cut off.
* Some of the numbers are chopped off. eg. see 5.6.

I am wondering whether the formatting of the whole document is as intended. It seems to be very big text on the page. Perhaps there is some strange font substitution going on? For example, Chad Fowler's forward used to take about 3 pages with wide margins. Now it takes 4 pages with very narrow margins. 

There are no page numbers or headers/footers.

Going to a chapter, there is no indication of its chapter number. For example, the "Data Structures" heading doesn't indicate that it is chapter 6. You can only tell it is chapter 6 because the next subheading is 6.1.

There is now only 1 level of bookmarks in the Bookmarks pane. (using Acrobat Reader DC)

**Comment by robconery** [comment]
Yep - that's the issue :). I messed with the font size as precisely as I could; on some readers it was far too small so I bumped it to 15px which rendered nicely on my screen. And yes, no header/footers this time.

And yes, the formatting is as intended - full parity with the epub. Also: yes the bookmarks would only give me one level, annoyingly.

Unfortunately I'm at a point of diminishing returns. My next step is to throw PDF out entirely; it's causing way too many headaches.

**Comment by ivansvlv** [comment]
I just discovered this feedback page, unfortunately I've already sent and email to pile up your mailbox! Sorry for that!! If you read this before an email, please disregard it as I wanted to report the same issue :/

Enjoying your book, top-notch!

**Comment by robconery** [comment]
I've updated the PDF and will be sending out a new release in a day or so.
