### ISSUE TITLE
Chapter 11.4.4 Inconsistency

### ISSUE THREAD

**Issue by Jaxelr** [robconery/feedback#208]
Hi, (Version 1.3)

I think there is inconsistent info at the chapter 11.4.4 on the paragraph mentioning the FollowtheData.com stats,.

(Page 459-460 on epub version)
On the third bullet its mentioned that Facebook collects 600 petabytes a day, but on one of the following bullet points it says Facebook stores 300 petabytes.

**Comment by robconery** [comment]
If you click the link you'll see that this is the case; data collected != data stored. I can't vouch for the site's numbers, but I think I've relayed it accurately.
