### ISSUE TITLE
Suggestion: Discuss static analysis

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#21]
Carried from my previous issue...Pretty sure I know why you won't want to put this in the book, but it was an interesting branch of CS for me so here goes:

OK, OK, I'm a weirdo. I used to work in safety critical software engineering and I would rather write Ada than JavaScript. Elm really appeals because the compiler, apparently, tells you you've done stuff wrong. I use an IDE that tells me when variables are unused and shit like that.

The point is, there is an area of computing that very few people know about that is actually really helpful for writing better code. Static analysis tells you when you have unused variables, loop invariants, mis-matched types, even when you go outside array bounds (and how many security holes are caused by array bounds!?!?)

I just wondered if this was a topic worth exploring. So many beginner languages - especially the languages of the web (JS, PHP, etc), in my opinion promote terrible coding practices. They are weakly typed, make assumptions about what you want to do, let you do pretty much anything without question. I'd love to see an critique of some of this, some info on static analysis and how compilers and static analysis tools in certain languages can detect certain things and help you remove them, eliminating basic errors.

Perhaps this is beyond the scope of the book, and I acknowledge that this is highly opinionated. But perhaps you can add it to a wish list or something.

**Comment by robconery** [comment]
Marked for later - thanks!

**Comment by robconery** [comment]
Going to kick this to a later volume, perhaps. Thanks for the suggestion!
