### ISSUE TITLE
Monkey Functor

### ISSUE THREAD

**Issue by seanmay** [robconery/feedback#210]
A quick thought, based on the Monkey Functor in the functional video:

You might consider making an update to the Monkey in the video, to conform a little more closely to the concept of Endofunctors, which helps us along.

```javascript
// before
const Mappable = x => ({
  map: f => f(x),
});

// after
const Mappable = x => ({
  map: f =>
    Mappable(f(x)),
});
```

It's, perhaps a subtle change, but an important one. With the simple implementation change, I am guaranteed to get the same Functor type back (the reason it's an endofunctor), which means that I can keep chaining map over the result.

In the case of `Monkey` that is not currently accurate. You would be relying on the passed function to return the correct type, which is unhelpful.

Examples of endofunctors commonly seen in JS:

Arrays:
```javascript
[1, 2, 3]
  .map(x => x * 2) // Array<number>
  .map(x => ({ value: x }) // Array<{ value: number }>
  .map(JSON.stringify) // Array<string>
```

Promises (bastardized pseudofunctors, but nonetheless):
```javascript
fetch("/blogs") // Promise<Response>
  .then(response => response.json()) // Promise<any>
  .then(results => results.blogs.map(Blog)) // Promise<Array<Blog>>
```

Observables:
```javascript
Observable.of(1, 2, 3, 4) // Observable<number>
  .map(x => x * 2) // Observable<number>
  .map(x => `${x}`) // Observable<string>
  .subscribe();
```

The key is the new container instance wrapping the `f(x)`. Without getting a new promise back, after a `.then`, the whole thing sort of falls over.

**Comment by robconery** [comment]
Great stuff and I agree! Thank you...
