### ISSUE TITLE
movie files missing

### ISSUE THREAD

**Issue by compostbrain** [robconery/feedback#213]
I am trying to download video files and i get a message: Failed - No file

**Comment by robconery** [comment]
Little more context?

**Comment by compostbrain** [comment]
I bought the book and videos about a month ago. I have downloaded a few
previously by opening the provided links and clicking the download button.
This is no longer working for me.  I like to download them because then I
can control the playback speed which is not possible on the website.

Thanks,
Joel

**Comment by robconery** [comment]
Hi Joel - thanks I figured out the issue. I was doing some housecleaning at Firebase and decided it wise to delete the video delivery project :). The remedy, unfortunately, involves you downloading the video thing again :(.

Sorry for this. I had to reset the URL...
