### ISSUE TITLE
10.5 Cart.add_item

### ISSUE THREAD

**Issue by plinde** [robconery/feedback#214]
In working with 10.5's Elixir Cart example (pp. 344), I noticed the below behavior with the given code for add_item function. It looks just like a simple missing argument for the function (items). Unless I'm missing something, this seems like a good fix to the next rev of the book. 

Furthermore, including this as an intended 'mistake' might even be a good segue to a brief sidebar  discussion about what this Elixir expression means: **"add_item/2"** e.g. add_item() function expects two args.

Cheers,
Peter

```
defmodule Cart do
  def add_item(items, item) do
    items ++ item
  end
end
```
```
iex(19)> items = []
iex(20)> Cart.add_item(%{sku: "SOCKS", price: 12.00}) |> IO.inspect
** (UndefinedFunctionError) function Cart.add_item/1 is undefined or private. Did you mean one of:

      * add_item/2

    Cart.add_item(%{price: 12.0, sku: "SOCKS"})
```
vs. passing the proper arguments to add_item()
```
iex(19)> items = []
iex(20)> Cart.add_item(items, %{sku: "SOCKS", price: 12.00}) |> IO.inspect
%{price: 12.0, sku: "SOCKS"}
%{price: 12.0, sku: "SOCKS"}
```

**Comment by robconery** [comment]
Hi - sorry for the delay getting back to you on this :). I'm a bit confused with this and it's probably my fault :). The code you're showing here for `add_item` is the correct code from the end of the chapter, however I do step through quite a few issues getting there. The code I have here in front of me is working too - so can you walk me through the problem a bit more?
