### ISSUE TITLE
Lambda calculus - applying multiple values clarification

### ISSUE THREAD

**Issue by glaxaco** [robconery/feedback#216]
In section 3.1.6, the expression 

λx.λy.t 

corresponds to this lambda in JavaScript: 

(x => y => x + y);

How did t become x + y? Ayaka Nonaka's article uses t in a similar manner in her article on the Y Combinator, but to me t seems to come out of nowhere in section 3.1.6.

Thanks!

**Comment by robconery** [comment]
Good question - I should clarify that in the book. `x + y` is just the body of the function, which is represented by `t` in the lambda. The problem is you can't just tack on an expression in JS so I used `x + y`. 

I'll update the text.
