### ISSUE TITLE
Image for code snippets renders book unusable for some

### ISSUE THREAD

**Issue by zersiax** [robconery/feedback#218]
I responded to the news email sent by getdrip with this issue as well, but since I have no idea if replies to those emails actually reach anyone I'll make a point to post the issue here as well. It'll also help for visibility. TLDR: images instead of textual code snippets makes blind developers like me unable to use the book properly. Here's the email in full:
Hi,

Making the text snippets into images will make people cranky alright.
I am a blind reader of your book and this move will render the book
almost useless to me. I'd have to look up the corresponding github
code every time you refer to a code sample, breaking my focus and
disrupting my concentration. So although copy-pasting from the book
may be fail, this move is the biggest accessibility fail you could
have made.

Regards,
Disgruntled Developer

**Comment by robconery** [comment]
Yep got your note and yes, thank you. I didn't think of this and I should have. I'll make a fix for next rev.

**Comment by robconery** [comment]
Wanted to touch base on this - I'm working on a fix right now and, hopefully, it will address this problem. It involves me using InDesign which... isn't easy but it's fun to learn so I'll hopefully have something done in a week-ish.

**Comment by robconery** [comment]
Happy to update that the code issue is now fixed :) and it's rendering beautifully without the use of images! Should have an update out in about 3 days.
