### ISSUE TITLE
Typos found in 'The Big O' chapter

### ISSUE THREAD

**Issue by craigrbruce** [robconery/feedback#219]
Heya Rob, great book. I'm re-reading the Big O chapter as you suggested and came across this small typo on page 131 right at the bottom:

` sepcifically something that Carl Friedrich `

Cheers.

**Comment by robconery** [comment]
Thanks! So much for my spell checker…

**Comment by craigrbruce** [comment]
Lol .. it happens!

**Comment by craigrbruce** [comment]
Gah! .. another one on page 143.

`we’re ready to turn you lose on
something a bit more complex`

loose

sorry :(

**Comment by craigrbruce** [comment]
Possibly another: 

`If they’re going to answer questions on our dime, we have to make sure they do well!`

dime === time? or is that an american idiom i don't know?

(page 144)

**Comment by craigrbruce** [comment]
page 145:

`If you need to evaluate ever item in a list for a given` ... every

don't hate me

**Comment by robconery** [comment]
No worries! I wish I had the money to hire a proper editor :). I really appreciate it...

**Comment by robconery** [comment]
American expression - at least I think it is.

**Comment by robconery** [comment]
Hate you? Quite the opposite ... thank you!

**Comment by craigrbruce** [comment]
no worries. finished reading the chapter and enjoyed it very much. this book is a massive help - it's interview time for me again :/

on the 'editor' note ... and I'm sure you have all your tools already, but I've recently started using [Grammarly](https://app.grammarly.com/) which has really helped while writing doco/blog etc... just to catch silly things that are easy to miss. Thought it might be worth a mention.

Good luck with volume 2!

**Comment by robconery** [comment]
Yeah I started using it but it was *really* hard getting through a huge book. I might use their proofreader service though... or just pop for a professional editor.

**Comment by robconery** [comment]
Wanted to let you know 1) all of these have been fixed and an update is coming (with quite a few improvements in layout) and 2) I really really appreciate the time you spent letting me know!

**Comment by craigrbruce** [comment]
No worries, Rob. And thank you!
