### ISSUE TITLE
shell script example is confusing

### ISSUE THREAD

**Issue by alj1s** [robconery/feedback#22]
At the top of page 64, bottom of 63 you create a shell script to run a build that takes a parameter.
Where you run the script you don't pass a parameter so it's a little misleading.

**Comment by alj1s** [comment]
I think it would be clear to give an example where 'redfour' is hard-coded in the script and then go on to explain how you can reference parameters via $1, $2 etc

**Comment by robconery** [comment]
That was another late addition that muddied things a bit. It's fixed...
