### ISSUE TITLE
Mobi file too large to be uploaded to Kindle

### ISSUE THREAD

**Issue by joshpuetz** [robconery/feedback#222]
The .mobi file in version 2.0 is now 85 megabytes large. The limit for emailing a .mobi file to Kindle for on Gmail is 25 megabytes. The limit for uploading via Amazon's OS X based uploader is 50 megabytes.

**Comment by robconery** [comment]
Unfortunately, to bring the size down I would need to remove half of the images, which means I would need to use some time of text/code formatting which means it will look like crap again when it gets reformatted by the Kindle.

I don't have an answer for this.
