### ISSUE TITLE
Images on Kindle are quite faint

### ISSUE THREAD

**Issue by GaProgMan** [robconery/feedback#223]
Originally reported on twitter [here](https://twitter.com/dotNetCoreBlog/status/894612249553326081)

When reading the pre-release to current (as of creation of this issue) version of the book on a Kindle 3rd Gen ([3rd gen Kindle on wikipedia](https://en.wikipedia.org/wiki/Amazon_Kindle#Third_generation)), images appear very faint. The following is an example (taken from my original tweet about the issue)

![images on Kindle 3rd gen appear quite faint](https://pbs.twimg.com/media/DGpNBJNXUAAJW5i.jpg)

I was originally convinced that this is due to my Kindle being old (it was bought in around 2010), or related to a common Kindle issue where the screen being to fade after a few years of use (thankfully, mine is still going strong).

However, this was also reported by twitter user [devspeed](https://twitter.com/devspeed), on a Kindle Voyager, in a reply to the above mentioned tweet. devspeed's example image:

![devspeed's example, showing faint images on Kindle devices](https://pbs.twimg.com/media/DGuBjhbUQAAdjOy.jpg)

**Comment by robconery** [comment]
It looks like only *some* of the images are faded? The code at the bottom is an image and it looks OK to me from here.

My guess is that the Kindle is rescaling the image, somehow making it look crappy. As with *every single release* of this book, the Kindle is causing me headaches. I'll do what I can.

**Comment by robconery** [comment]
Found the problem; should be fixed in latest release.
