### ISSUE TITLE
Typo on "Chapter Six: Data Structures" - "try"

### ISSUE THREAD

**Issue by dance2die** [robconery/feedback#225]
Context: This applies to **Version 2.0** of the book.

There is a typo in Chapter Six: Data Structures, where the book describes a *trie* but written as *try* as shown below.

FYI - I found the typo in all three formats (.epub, .mobi, & .pdf)

![typo - try](https://user-images.githubusercontent.com/8465237/29235342-11f4c622-7ecc-11e7-99be-1156b1d86be8.png)

**Comment by robconery** [comment]
Thanks! fixed...

**Comment by dance2die** [comment]
You're welcome & Thank you.
