### ISSUE TITLE
Version 2.0 - Lambda Images are too small on EPUB & Mobi versions

### ISSUE THREAD

**Issue by dance2die** [robconery/feedback#226]
Hi Rob,

In "Part 1: History -> Chapter Three: Lambda Calculus", images used for Lambda are a bit small even after increasing font sizes.

I read that all code samples are now images, and I wonder if images below can be increased in EPUB & Mobi versions. (FYI - PDF version is fine).

Thank you.

* EPUB version
![images too small-epub](https://user-images.githubusercontent.com/8465237/29235638-6b0bfaa8-7ece-11e7-909a-263d5830d911.jpg)

* Mobi version
![images too small-mobi](https://user-images.githubusercontent.com/8465237/29235641-6e5c0fcc-7ece-11e7-8b8a-5449593ccd78.jpg)

**Comment by robconery** [comment]
Well... like I mention in the first part of the book: I sized the font to match the images and if you change the font size the images won't scale. The reverse is true for code as text - if you tweak the font size it blows up the formatting altogether (and in some cases renders it with the chosen font. 

In every reader that's not a Kindle, the images will maintain size just fine. I don't know what your settings are here - but I can tell it's a Kindle. Kindle's are giving me migraines. 

As you might imagine, if I resize the images to fit your device, it will blow up for someone else's.

**Comment by dance2die** [comment]
I am sorry that I should've read the first part one more time before creating a ticket.
And thank you for including other formats like PDF, which let me able to read without a problem.

**Comment by robconery** [comment]
Ha - no worries :) it's a whole book - hard to spot little changes like that. I've been thinking about this non-stop; it's a huge problem and I need to figure out how to do reliable code samples across book versions. I'm going to leave this open if you don't mind.

**Comment by dance2die** [comment]
Thanks, Rob.
Please leave this issue open if it could be helpful :) 👍

**Comment by robconery** [comment]
OK I think I have a fix on this one - the images were getting rerendered from the converter I was using. Moreover I've figured out the code formatting so... another drop coming in a few days.

**Comment by dance2die** [comment]
Alright~ Thank you, Rob.
