### ISSUE TITLE
Formatting issue - Unnecessary bullet point

### ISSUE THREAD

**Issue by dance2die** [robconery/feedback#228]
Hi Rob,

On page 308, I believe that "The disadvantages are:" has an unnecessary bullet point.
Let me know if this is intentional or not.

Thanks~
![pdfxcview_2017-08-17_19-14-43](https://user-images.githubusercontent.com/8465237/29437731-77f351d8-8380-11e7-8847-4d3d22e02129.png)

**Comment by robconery** [comment]
Bleh. Fixed :).
