### ISSUE TITLE
Copy/Paste warning on Chapter 10

### ISSUE THREAD

**Issue by dance2die** [robconery/feedback#230]
Hi Rob,

In Chapter 10 (Page 319), there seems to be a sentence that seems to be invalid in v 2.0.
![pdfxcview_2017-08-17_19-22-25](https://user-images.githubusercontent.com/8465237/29437985-f4b1ca96-8381-11e7-82d9-976c10f76a85.png)

Because, in `A Word of Formatting`, there is an instruction that all code samples are images (therefore can't copy nor paste)
![pdfxcview_2017-08-17_19-21-41](https://user-images.githubusercontent.com/8465237/29437943-be6f200a-8381-11e7-96b4-47170524eb4a.png)

**Comment by robconery** [comment]
Thanks - this is now valid again as I've put the code back... but I still removed this sentence :).
