### ISSUE TITLE
Page 305 - Editing - mentioning earlier information that was not given

### ISSUE THREAD

**Issue by oferze** [robconery/feedback#232]
![image](https://user-images.githubusercontent.com/5157769/31589329-73d7eaee-b208-11e7-85dc-815e87ca04b7.png)

"as we've discussed" - this was not discussed before. The text said that the stack is for value types and the heap is for reference types, like this quote from page 302:

![image](https://user-images.githubusercontent.com/5157769/31589347-a9e37b62-b208-11e7-87db-8b9eef46710c.png)

**Comment by robconery** [comment]
Thanks again :) fixed.
