### ISSUE TITLE
Page 307 - Typo

### ISSUE THREAD

**Issue by oferze** [robconery/feedback#233]
![image](https://user-images.githubusercontent.com/5157769/31589372-11517a6a-b209-11e7-9280-4fdb9fc84597.png)

Should be **are** using (or better - change to present simple: _Both Java and .NET use tracing for GC, both of them implement various flavors..._

**Comment by robconery** [comment]
Bah - dumb sentence don't know why happened there :) it's fixed. Thanks again!
