### ISSUE TITLE
Page 185 - Syntax error

### ISSUE THREAD

**Issue by oferze** [robconery/feedback#234]
The first Fibonacci function has a syntax error at this line:

![image](https://user-images.githubusercontent.com/5157769/32263982-0a2f6d44-bee5-11e7-9770-5cfc00b2c8c1.png)

`fibCount` has not been declared and is not being used; this line should be omitted (it is being used in the next code example and I believe it's been partially copy-pasted to the first one).

**Comment by robconery** [comment]
Oh LORD. That was from the example where i was counting the iterations. Damn! Thanks!
