### ISSUE TITLE
Page 191 - Redundant function parameter

### ISSUE THREAD

**Issue by oferze** [robconery/feedback#235]
The first example of a greedy algorithm for calculating a Fibonacci series has this first line:

![image](https://user-images.githubusercontent.com/5157769/32264060-798a3642-bee5-11e7-8773-3eda8b9e00ed.png)

But `fn` is not being used in this code snippet. It's only introduced and being used in the next one.

Similarly, the line:

![image](https://user-images.githubusercontent.com/5157769/32264125-d5ff952a-bee5-11e7-996f-5122e8e678b2.png)

is also redundant as it's only applicable in the next code snippet.

**Comment by robconery** [comment]
Thanks... fixed...
