### ISSUE TITLE
Bellman-Ford optimization

### ISSUE THREAD

**Issue by Borzik** [robconery/feedback#237]
Hello! First of all, thank you for this great book!
I'm reading Bellman-Ford chapter now, and "Analysis and Summary" part says:
>There is room for improvement, however. Think about the process we went through in the first section. I only needed 3 total iterations to derive the shortest paths. The code I wrote, however, required 5. How would you optimize this?

And a bit earlier it says:
> You’ll notice that I’m only iterating to vertices.length – 1. Can you reason why?...

I accepted this challenge and used the code you provided [here](https://github.com/imposters-handbook/videos/blob/master/algorithms/dynamic_programming/bellman-ford.js), with small alteration so see number of iterations and incoming memo:
```js
for(vertex of vertices){
  console.log(memo);
  if(!iterate()) break;
}
```
Its output is:
```js
{ S: 0, A: Infinity, B: Infinity, C: Infinity, D: Infinity, E: Infinity }
{ S: 0, A: 4, B: 8, C: 10, D: 3, E: -5 }
{ S: 0, A: 4, B: 8, C: 6, D: 3, E: -5 }
{ S: 0, A: 4, B: 4, C: 6, D: 3, E: -5 }
```
So it required only 4 iterations to complete. And the 4th one is executed to verify that we already have the solution. I guess older version of this book had a bit different code which was then updated to be more optimal, but wording stayed the same. Or I am missing something, and if so — please correct me. Thanks!

**Comment by robconery** [comment]
Hey Felix - I’ve been meaning to get back to you on this but haven’t had the time. I need to look through it some more; gimme a few weeks?

**Comment by Borzik** [comment]
Yeah, no worries, I've already completed reading this book and it's fantastic!
Will look forward for your reply, thanks!
