### ISSUE TITLE
quick sort code question

### ISSUE THREAD

**Issue by compostbrain** [robconery/feedback#238]
I really enjoy your book and videos.  I have a quick question about a code sample. In the quick sort javascript code I don't understand the reason for the concat in the line where you remove the pivot point. I think that `list = list.slice(0,pivot).concat(list.slice(pivot + 1));` could be shortened to `list = list.slice(0,pivot);` without any effect on the outcome. Am I understanding this correctly or can you explain the need for this?

**Comment by robconery** [comment]
You're pushing two lists together without including the pivot itself. I suppose the code could be improved :).
