### ISSUE TITLE
Typo: Unbuntu

### ISSUE THREAD

**Issue by alj1s** [robconery/feedback#24]
Page 89
Setting up a web server
Nodejs
First sentence states Unbuntu rather than Ubuntu.

I know that you state that you have an editorial team poring over it for typos so I've ignored most of the ones I've seen, but I'm not assuming that the team is technical, so anything not grammatical or likely found in a standard dictionary I'm assuming is fair game. Let me know if this is not the case.

**Comment by robconery** [comment]
No problem at all - thanks. Also: I don't have the same page setup as you (font size and OS are different) so if you could tell me the sections I'd appreciate it.

**Comment by alj1s** [comment]
Ah yeah. Course. Will do.
