### ISSUE TITLE
Formatting of Y Combinator 

### ISSUE THREAD

**Issue by differentsmoke** [robconery/feedback#240]
This is more of a matter of opinion, maybe, than an error, but I'm having a lot of trouble reasoning through the lambda calculus chapter, and though most of it is clearly the difficulty of the subject, i feel some of it has to do with formatting and the way  some concepts are introduced.

Some suggestions: 

Please don't write the Y Combinator (the hardest concept in the chapter) in a different format than all other lambda expressions. It makes it hard to compare with what we already (think we) understand.

Also, I feel some baby steps are skipped unnecessarily. We never see application of two variables in lambda Calculus until it pops up in the ES6 examples. For the most part, this examples repeat what was shown as abstract lambda calculus expressions, which is very helpful. But when a familiar programming concept appears only as programming, I have some difficulty mapping it back to lambdas.

Finally, I feel a  "function" statement, while more verbose, would actually be clearer than all those arrow functions.

**Comment by robconery** [comment]
Help me understand the issue a bit more? You mention you're having a hard time understanding some things, but you don't mention what they are. I'm happy to help if you tell me the issue. As to the particulars:

>Please don't write the Y Combinator (the hardest concept in the chapter) in a different format than all other lambda expressions. It makes it hard to compare with what we already (think we) understand.

Which format are you referring to? Font? I'm looking at it now and I used a Math font for a formal math declaration, which is used throughout the book. Is this what you mean? I also used ES6. Help me understand?

RE the application of two variables, what's causing the issue? I showed them as both a reduction and with code. I'm fairly certain I didn't skip any steps, so if you could tell me what you're missing it would help.

I will differ with you entirely on a `function` vs. an "arrow". I wrote it this way to communicate clearly what a lambda expression is.

It sounds to me, and this might seem rather direct so forgive me if it comes across as rude - but it sounds to me like you're having trouble understanding something and have decided that's _my_ fault. Which is fine - it could very well be the case! However, a Q&A would be a nice thing before we decide that a chapter I've redone 4 times needs a 5th go :).

**Comment by differentsmoke** [comment]
Hi Rob, 

Starting from the bottom up, I am fully aware that this is a very hard subject. I'm sorry that it reads like I'm blaming you, it should've been expressed as an improvement not as a fix.

(I started to suspect I may not be reading the last version as well. I think I'm on 2.2, but on the Markov Chain section was a reference to a missing diagram that makes me doubt if this is a final version of not. I think you sent this one on August)

Regarding arrows vs functions, I agree that this is more of an opinion sort of thing, but to me the way code is helpful in that chapter is to ground abstract concepts, and not to show you how to write in lambda style. I'd prefer more legible code that looks less like a Lambda expression (but the legibility thing may just be my dinosaur ES5 bias).

 Regarding skipping steps: it may be that I don't get something, so I'm assuming imaginary steps, but I feel that by the time we this snippet appears on page 50

(x => y => x + y)(2)(3)

We haven't done anything of that complexity as a Lambda and won't do until the top of page 54. 

Finally, regarding Y Combinator formatting, up until the Omega Combinator on page 58, all lambdas have been done in monospaced   font like the one for the code examples, but then on page 59 the y Combinator is suddenly in this serif mathematical typeface. It made it harder for me to go and cross reference to the Omega Combinator.

I hope this clarifies it, and again sorry if this felt like an attack. I do regret the tone of my original comment, could've used more politeness and less terseness.

Thanks for getting back to me!

**Comment by robconery** [comment]
No need for apology :) I don't mind being challenged one bit. Generally I like to understand the motivation behind suggested improvements.

Also: you do have latest. There's a bug with the Markov chain thing :(.

RE arrows: I dig that you're more familiar with `function` and that's more legible to you. I can also understand why it seems that I'm doing using lambdas to show people how to write lambdas. That's not the case. A lambda expression is indeed shorthand, but it's also something much more! It's one step closer to a functional style that stems from Lambda Calculus. I read this as you not being familiar with ES6/lamdas, which is completely fine, but I would urge you to explore these little nuggets as they move you away from more formalized coding to more of a functional style.

>We haven't done anything of that complexity as a Lambda and won't do until the top of page 54.

This could be a matter of me writing things more clearly. The top of the section (p 49 on PDF) is entitled "Applying Multiple Values", where "Applying" means function invocation. The first expression seen is a lambda:

```
λxy.t
```

Two variables (`x` and `y`) with a function body `t`. That is equivalent to this expression (which is detailed in the next paragraph):

```
(x => y => x + y)
```

From there, substitution is discussed as well as different ways of thinking about multiple variables/values.

I *think*, and I hope I don't sound elitist, but I think that maybe your unfamiliarity (if that's the case) with lambdas might make the expression `(x => y => x + y)(2)(3)` look more complicated than it is? 

RE Y combinator - I see what you mean, but this *is* a formal math declaration and *not* lambda calculus (the term `f(x)` isn't valid LC). I do see why that would be confusing as there are indeed lambdas in there :). I'll tweak that a bit more for the next version.

**Comment by differentsmoke** [comment]
Thanks again Rob. Some further comments:

**RE arrows**: Yes, I guess it is a matter of familiarity / opinion. And I can always use Babel to get an ES5 version 😉 

**RE Y Combinator**: I think all that is needed would be to have a version that is expressed in the same way as the Ω Combinator, before showing the mathematical definition. That way you can look at Ω and Y, and easily see how they're similar and how they're different (my issue with the change of format is that it hides its similarities, makes comparison unnecessarily harder).

Finally, **RE ES6 examples** and "skipping baby steps", my issue is not with the defined function
```
(x => y => x + y)
```
But with this part:
```
(2)(3)
```
I understand the JS. `(3)` is passed to the function returned by passing `(2)` to the first expression, namely `(y => 2 + y)`. My issue is that up until that point we have never made a reduction with two terms (not sure if this is the correct terminology) in Lambda calculus form.

Does that explanation make sense? If I'm still not getting something, please let me know.

**Comment by robconery** [comment]
I'm wondering again if we're looking at the same edition. Specifically:

>My issue is that up until that point we have never made a reduction with two terms

That's this:

<img width="494" alt="screen shot 2018-01-30 at 8 50 42 am" src="https://user-images.githubusercontent.com/78586/35579089-aed9aad4-059a-11e8-99cc-701f99637994.png">

I further move on to this:

<img width="471" alt="screen shot 2018-01-30 at 8 51 11 am" src="https://user-images.githubusercontent.com/78586/35579122-c571d74e-059a-11e8-9556-8d3fad3dfa05.png">

And finally end up with this:

```js
(x => y => x + y)(2)(3);
```

This seems to be what you're asking for and I don't know how else to lay it out.

**Comment by differentsmoke** [comment]
Ok, then I guess we hit the crux of my misunderstanding:

Isn't this...
```
λx.λy.y x
```
...equivalent to this...

```
(x => y => y)(2)
```
...?

When I say "with two terms" I mean one where two terms are applied. We go from applying one term in lambda calculus, to applying one term in JS, to applying two terms in JS. 

This confused me. I may be asking for more detail that it is practical. Still, I wanted to make sure you understood where my point of confusion was.

**Comment by robconery** [comment]
Yikes. That's a bad example - no those aren't equivalent. The first is a weird application where `x` is both bound and free. In *structure*, yes those are the same. 

I'm having a really difficult time trying to get to the thing that's sticking you. *Yes*, the chapter goes from single expressions (and application) to multiple, *that's the name of the section*. It starts off with a discussion of *currying*, which means splitting `λxy.t` into this `λx.λy.t`.

The book I'm looking at demonstrates multiple values in LC, then JS, then reduction in LC, then reduction in JS, then application in JS. There are no literal values in LC - is this what's causing the problem?

Taking a few steps back: are you not understanding what's going on, or are you having an issue with the way I wrote it?

**Comment by differentsmoke** [comment]
When is the first time you demonstrate the *application* of multiple values in LC?

**Comment by robconery** [comment]
This thread's long enough and we're going in circles. I'm sorry you're having difficulty with this chapter, but there's only so much I can do. At some point we're just going to niggle this into the ground and yes, we'll discover that it's not perfect.

If you want a refund I'm happy to provide. For right now I need to close this off.
