### ISSUE TITLE
Hardcover Functional Programming Section

### ISSUE THREAD

**Issue by nhyne** [robconery/feedback#250]
I'm seeing multiple issues with the hard cover copy of the book in the functional programming section. On page 295 there is a section discussing the outputs of a function with a colon for the outputs, but nothing is printed. 

On page 300 there are two code blocks that are supposed to be different but are identical.

**Comment by robconery** [comment]
Thanks. Does “multiple” =2 or are there more?

**Comment by nhyne** [comment]
Those were the only two that I found at the time.
