### ISSUE TITLE
Typo? "multiples of 2 are 2, 4, 6, 8, 16"

### ISSUE THREAD

**Issue by mirka** [robconery/feedback#251]
On page 100 of PDF v2.2.0:
> We’re programmers and have a reasonable facility for base 2 multiplication, hopefully. We know that multiples of 2 are 2, 4, 6, 8, 16, 32, 64 and finally 128. The number we want is somewhere between 64 and 128, so we round up to be safe. This gives us 7.

Given the context, it seems like this should be "**powers** of 2" rather than "multiples of 2". But even if the word choice there was intentional, shouldn't the number sequence at least be "2, 4, 8..." and not "2, 4, **6**, 8..."?

**Comment by robconery** [comment]
Yep - nice catch :).
