### ISSUE TITLE
Hardcover page 40 typo

### ISSUE THREAD

**Issue by holmberd** [robconery/feedback#253]
At the bottom of page 40 it reads:

>  help your team **think** **approach** the problem with care.

Most likely it should be 

> `help your team approach the problem with care.`

On a separate note, I experienced some difficulty in trying to verify if this issue had already been closed. Searching through open/closed issues becomes tiresome as the number of closed tickets increase, which increase the likelihood of the same issue being raised multiple times. It would be nice if the issues adhered to the same keyword structure, for ease of searching, e.g. `<publication media><page n><problem>`, `<general><problem>` or some other form of consolidation.

Thank you :)

**Comment by robconery** [comment]
Thanks for letting me know. I won't be able to send a new hardcover out, but I can make an update for later revisions.

RE the issues list - are you suggesting I edit the titles? A good idea, but in the very beginning I was dealing with a TON of issues. Also, the "page N" problem is a big one as PDF <> Print <> Kindle/epub.

**Comment by holmberd** [comment]
@robconery an update for later revisions was all I had in mind. A new hardcover would be too much hassle and a pen works perfectly fine.

As for the issues list, I was thinking more in the line of adding a note to the README, specifying to include the publication media, i.e. PDF, PRINT, KINDLE and page number, in the title.
