### ISSUE TITLE
03-database-normalization video is not actually 3rd normal form

### ISSUE THREAD

**Issue by rmsaddler** [robconery/feedback#254]
**Great book and video series!**

The final version of the normalised database in the video isn't quite right because the rentals table has the same rental number in more than one row.  This is because there is a many-to-many relationship between rentals and films that has not been captured by the schema design so rows are being duplicated for each film in the rentals table.

The correct multiplicity for the 3 entities is:

[customers] 1...∞ [rentals] ∞...∞ [films]

As there is a many-to-many relationship, the suggestion is that there should be a 'link table' called rental_films to model the relationship between rentals and films that has rental_id and the film_id as columns.

**Comment by robconery** [comment]
Thanks for bringing this up - nice catch! Indeed - I didn't notice before that the rental number is duplicated, which is a bummer. Yep - your `rentals_films` (or maybe `rental_items`) would work fine.

Ah well.
