### ISSUE TITLE
Missing expression on page 47 in the PDF

### ISSUE THREAD

**Issue by vesteraas** [robconery/feedback#255]
There seems to be missing an expression after the first section under the title **Bound and Free Variables**  on page 47.  The next section starts with _"In this expression we’re dealing with two variables: x and y."_ but I'm not seeing any expressions.

**Comment by robconery** [comment]
Yeah I think it's missing a diagram. Which version are you reading?

**Comment by vesteraas** [comment]
Version 2.2.0
