### ISSUE TITLE
Logs of binary tree levels incorrect.

### ISSUE THREAD

**Issue by dunxen** [robconery/feedback#256]
I'm not sure if this issue has been raised / corrected yet, but I recently bought the EBook version and came across this:

![screenshot 2018-11-02 at 08 08 21](https://user-images.githubusercontent.com/3072149/47896582-d5d7d880-de76-11e8-9d4b-96dd78427f78.png)

I assume you meant to use powers of 2 (**2^0 = 1, 2^1 = 2, 2^2 = 4**), or **log2(1) = 0** etc.

**Comment by robconery** [comment]
Yeah it's been mentioned - thanks for letting me know :).
