### ISSUE TITLE
Finding duplicates in Big-O chapter can be done in O(n)?

### ISSUE THREAD

**Issue by mpnordland** [robconery/feedback#258]
So based on Assumption 1 on page 97, it seems to me that checking the list for duplicates
can be done in O(n) complexity. Since the list is sorted, any duplicate elements will be located together.
This means that all we should have to do is check the next element to see if it matches our current element. If it does, then the list has duplicates. If we reach the end of the list without finding a duplicate, then the list doesn't have a duplicate. I understand this to be O(n). Have I understood things correctly?

Here's how I coded it:
```python
def has_duplicates(iterable):
    for i in range(0, len(iterable)):
        if i == len(iterable) - 1:
            return False
        elif iterable[i] == iterable[i+1]:
            return True

print(has_duplicates([1, 2, 3, 4, 5, 6,6, 6, 7, 8, 9, 10]))
```

**Comment by robconery** [comment]
Indeed - O(n) is doable for checking for duplicates if you use a hashtable to remember what you've iterated over - all you need is a single loop and then check for the key in your hash. If it's not there, add the value in your loop.

If it's sorted we can do _better_ than O(n), which is the point of the section you're on - using binary search/remove which gets you to O(log n). Either way - you're assumption is correct but you'd still need to traverse the entire list.
