### ISSUE TITLE
Very Minor: Dual Use of "1930s and 1940s" on Page 13.

### ISSUE THREAD

**Issue by davidshq** [robconery/feedback#259]
On page 13 in the third paragraph you note that "Researchers began to design electronic computers in the 1930s and 40s..."

On the same page in the fifth paragraph you note that, "better computation ramped up in the 1930s and 40s..."

Would this be improved by removing the latter references to the 1930s and 40s since we have already established this as the time period in the third paragraph?

e.g., the latter might be revised to "better computation ramped up as war broke out..."

The more I think about this the less I think it is worth the words I've used to describe it.

**Comment by robconery** [comment]
Thanks David - I've rewritten the entire chapter so this hopefully is dealt with.
