### ISSUE TITLE
Errors in heap sort

### ISSUE THREAD

**Issue by luddd3** [robconery/feedback#26]
In the heap sort section there are some issues. The citations are taken from the pre002 pdf version where the "log" in O(n log n) has disappeared.

> Heap sort is O(n n), however it has the advantage of being O(1) if the list is already sorted, as opposed to merge sort, which needs to do a single scan, making it O(n). Given this, heap sort is useful if data may be already pre-sorted or of the same value

No sorting algorithm can be better than O(n) unless the algorithm knows that the input is already sorted (and why sort it then?). They have to look at each element in the list at least once.

Merge sort is O(n) during a special case when it is fed with input which has sequences of sorted data, but that is a special variant of merge sort. Regular merge sort has best case performance of O(n log n).

Heap sort best case performance is O(n log n) unless the special, but very unusual, variant smoothsort is used with input that is already partially sorted. With smoothsort O(n) can be reached.

> It's hard to beat an optimized quick sort, however if the worst-case complexity ever comes into play with your quick sort O(n^2)), then heap sort is a good alternative as it's always O(n n) and in the worst case is actually O(1).

This paragraph is was a little bit strange if you consider the earlier reasoning.

**Comment by robconery** [comment]
Yep - I misread and essentially completely screwed things up. This is fixed now :).
