### ISSUE TITLE
Potential code bug in PDF version of Imposter's Handbook v2.2 on Page 102 (Big O)

### ISSUE THREAD

**Issue by dpehrson** [robconery/feedback#265]
The implementation of `hasDuplicates` contains the following code:

```
if(searchFor(nums, num)) {
  return true;
}
```

However, if `num` was zero and was present in `nums`, this would not work out as expected due to the way truthiness is handled in Javascript.

I believe this should be updated to:

```
if(searchFor(nums, num) !== null) {
  return true;
}
```

**Comment by robconery** [comment]
Damn good catch! Fixed and updated thank you.
