### ISSUE TITLE
Linux section introduction suggestions

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#27]
Hi. Sorry. Do tell me to leave you alone if you want.

I feel like the Linux section needs an explanation of why readers are about to be instructed to do some things.  The book dives straight in to Docker instructions without telling people what they are about to do with Linux. I found myself wondering: am I supposed to be following along with this, and if so why? Where am I headed with this? Will the book not make sense if I'm not practically following along?

Perhaps the opening "Linux" chapter page could say something like: "We have to know Linux. It's the essential skill. In the following chapters I'll explain how you can install Linux and we'll learn the basics of using Linux commands. Don't worry if you can't follow along, the book will still makes sense and you'll still learn."

Or possibly: "be sure to follow along if you can - having a working Linux OS will be essential for later exercises"

If you don't mind a bit of repetition, the first page of "The Tools" could also use an explanation of what we're about to do and why.

"We're going to work together on some exercises to learn Linux. It's helpful to have a Linux machine to poke around on. Just 10 years ago the notion of..."

**Comment by ghost** [comment]
Yeah, the Docker and Digital Ocean bits need a bit of clarification. When I first got to the section on Digital Ocean I thought "Hang on, why do I need to do this if I've just set up Docker?" I went back and saw the heading; "The Easiest Thing" and "The Recommended Thing", but I think it could do with and introductory sentence. Something like 
"... let's get you setup.
I'm going to show two ways to get a Linux machine, an easy way and a recommended way. Choose which ever blah blah"
I'm experienced with both and I had to go back and re-read this bit.

**Comment by robconery** [comment]
Yep - this is all getting reworked.

**Comment by evankline** [comment]
I was also a bit confused at this point. The line in this section that says if you're on a Mac you can skip ahead gave no place to skip ahead to.

**Comment by robconery** [comment]
Reworking all of this currently - fixing this (and more)...
