### ISSUE TITLE
Typo in v2.2.0 EPUB, Big O, The Not So Good Approach: O(N^2)

### ISSUE THREAD

**Issue by hughbien** [robconery/feedback#270]
In the Chapter "Big O", in the section "The Not So Good Approach: O(N^2)".

The code example is:

```js
const hasDuplicates = function(num){
```

I think `num` parameter should be pluralized, because the argument is actually an array of numbers and `nums` is referenced in the function body.

**Comment by robconery** [comment]
Nice catch! Agree - thanks!

**Comment by robconery** [comment]
Cheers thanks!
