### ISSUE TITLE
"Church" listed along with Babbage, Lovelace and Turing without any previous mention.

### ISSUE THREAD

**Issue by industriousparadigm** [robconery/feedback#271]
In page 14, after a series of mentions of Charles Babbage, Ada Lovelace and Alan Turing, a paragraph reads: "In terms of computation, all the hard work was done by Babbage, Lovelace, Turing and **Church**."

This last name, Church, is never before mentioned in the book, unlike the 3 others. The sentence clearly expects the reader to have seen that name mentioned before, as the others were, so it looks like a mistake to me - perhaps earlier drafts of the book included paragraphs explaining who Church is?

P.S. - bought the book today, thanks for putting the effort into it! Fascinating read so far 👏 👏

**Comment by robconery** [comment]
Cheers thanks :) yeah I moved some chapters around… Alonzo Church and Lambda Calculus used to be before this chapter. Appreciate it and glad you’re enjoying!

**Comment by robconery** [comment]
Rewrote the chapter on Computation so hopefully this issue is resolved :) thanks again.
