### ISSUE TITLE
S1 pdf, page 38: freshman should be freshmen

### ISSUE THREAD

**Issue by industriousparadigm** [robconery/feedback#273]

**Comment by robconery** [comment]
? In what sense? I'm only a single person here.

**Comment by industriousparadigm** [comment]
"a client that wanted to enrich the lives of college freshman"

Are we not talking about many college students here?

**Comment by robconery** [comment]
🤦 ha doh... damn I see it... derp I thought it was a reference to me in college. Thanks mate appreciate it :).
