### ISSUE TITLE
S1 Page 110, a broken link

### ISSUE THREAD

**Issue by farskid** [robconery/feedback#277]
## Where'd you find this? Page number from PDF would be helpful
PDF version in page 110

## What's the problem? 
The link to `my github repo` is missing `:` after `https`.

This is what I read:
```md
//put it in here
You can find the code used in parts of this section up at [my github repo](https//github.com/imposters-handbook/sample-code/tree/master/algorithms).
```

This is what I think it should be:
```md
//put it in here
You can find the code used in parts of this section up at [my github repo](https://github.com/imposters-handbook/sample-code/tree/master/algorithms).

```
## How are you reading the book?
Version 2.2.0 PDF on Mac OS using the Preview application.

**Comment by farskid** [comment]
It might be worth mentioning that the other 2 links in the same section are broken as well.
These 2 links:
```
In addition, you can buy `17 video walkthroughs` of the algorithms you see in this chapter and others `from here`.
```

**Comment by robconery** [comment]
Oh wow! Thank you!

**Comment by farskid** [comment]
Sorry if this is jamming all the issues in a single thread but for some reason, those 3 links are not copiable from the PDF.
Looks like a unicode problem to me. Below is what I get by copying the text from that paragraph and pasting it somewhere else.

```
􏰪􏰝􏰗 􏰕􏰆􏰉 􏰥􏰉􏰌 􏰊􏰁􏰂 􏰕􏰝􏰌􏰂 􏰗􏰈􏰂􏰌 􏰄􏰉 􏰘􏰆􏰙􏰊􏰈 􏰝􏰞 􏰊􏰁􏰄􏰈 􏰈􏰂􏰕􏰊􏰄􏰝􏰉 􏰗􏰘 􏰆􏰊 􏰅􏰡 􏰇􏰄􏰊􏰁􏰗􏰜 􏰙􏰂􏰘􏰝. In addition, you 􏰕􏰆􏰉 􏰜􏰗􏰡 􏱁􏰒 􏰠􏰄􏰌􏰂􏰝 􏰔􏰆􏰋􏰢􏰊􏰁􏰙􏰝􏰗􏰇􏰁􏰈 of the algorithms you see in this chapter and others from here.
```

**Comment by robconery** [comment]
Yeah that's likely a thing between your reader and where you pasted from. I don't think I can help with that though I might have some ideas. OS? Reader?

**Comment by farskid** [comment]
Mentioned in the issue description: MacOS + the Preview app

**Comment by robconery** [comment]
Derp - LOL I keep doing that! Hmmm that's super weird I'm not sure how I can fix that.

**Comment by farskid** [comment]
I found out those links have the same issues in another section as well. The paragraph is reused I suppose so worth checking the whole book for it.



> Derp - LOL I keep doing that! Hmmm that's super weird I'm not sure how I can fix that.

I can try to use another reader and verify the unicode problem.

**Comment by robconery** [comment]
To be perfectly honest copy/paste isn't a priority and that's not to dismiss your thought at all... but it's not something I'm considering a "use case". Push back if I'm being short-sighted.

**Comment by farskid** [comment]
Nah, that's fine. it just makes note taking from the book harder but I can manage :)

**Comment by robconery** [comment]
Fixed the github link...
