### ISSUE TITLE
S1 Page 132, Grammar issue

### ISSUE THREAD

**Issue by farskid** [robconery/feedback#278]
## Where'd you find this? Page number from PDF would be helpful
S1 Page 132

## What's the problem? 
There is a grammatical mistake.

This is what I read:
```md
//put it in here
Bits of data are stored in contiguous memory, so they are also have the smallest footprint of any data structure.
```

This is what I think it should be:
```md
//put it in here
Bits of data are stored in contiguous memory, so they also have the smallest footprint of any data structure.
```
## How are you reading the book?
Version 2.2.0 PDF on Mac OS using the Preview application.

**Comment by robconery** [comment]
Cheers fixed!
