### ISSUE TITLE
Bash, command line, terminal, ssh

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#28]
I know what these things are (and use them every day) but I feel like the relationship between them isn't explained well. I feel like a new reader would have a vague understanding of a bunch of things but without knowing why they are all necessary. It may be that a simple re-ordering or an explanation of what runs inside what might help.

E.g. On a Mac the terminal gives you a command line, which is your user interface. The terminal runs a shell. In the shell you can run SSH which securely connects to another computer (or your docker container). You're then running another shell on the remote computer.

On a PC PuTTY does the SSH to the remote computer, which launches a shell on the remote computer. PuTTY gives you a command line for giving instructions to this shell. You aren't running a shell locally,

But also you define the "shell" as an "interpreter" which is correct, but not a very helpful explanation of what the shell is and does to someone that doesn't know (and may even be confusing for someone that knows what a language interpreter is).

**Comment by stereobooster** [comment]
Note on `Bash`.

> The default shell is bash, or the Bourne Again Shell

It depends on the system. But bash is the most wide spread I suppose. All POSIX systems should have shell - it is requirement of [standard](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html). But implementation may differ and it is ok as long as it is compatible with standard.

**Comment by robconery** [comment]
Getting reworked, so closing for now.
