### ISSUE TITLE
Assumed knowledge and SSH help

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#29]
At the end of the Linux "The Tools" section you say "Using SSH is one of those things I'm assuming you know how to do."  The subsequent pages explain some fairly basic Linux stuff that I would expect people that know how to use SSH to also know. If people don't know about file modes, will they know how to use SSH?

Perhaps you could just add "If you don't know how to use SSH then you can get help at..." rather than leaving non-SSHers a bit lost at this point?

**Comment by luddd3** [comment]
Another perspective is that ssh is available on other platforms than Linux. A Windows user might very well know ssh but not the basic Linux stuff.

**Comment by robconery** [comment]
Both good points. I'll add a blurb on SSH - I was thinking that most readers would at least understand what it _is_ ... but I should probably add a whole chapter on it, including things like SCP, PEMs etc.

**Comment by rosswintle** [comment]
That's a fair comment. But equally, there may me Linux users who've never SSH'd and a Windows user that doesn't know about SSH at this point will be as stuck as a non-Windows user that doesn't know about SSH. Perhaps my logic was wrong, but I think the comment still stands.  If you've assumed your readers don't know about file modes and sudo, they're probably pretty new to the Linux world, and so can you assume they know about SSH?

**Comment by robconery** [comment]
I'm not sure if you're responding to me or not - but as I mention I'll expand on SSH. I would also say that there _is no way_ that a Linux user doesn't know SSH. Won't happen.

**Comment by rosswintle** [comment]
Thanks!

I know several Mac users who dip into the terminal (and therefore kinda become Linux users) for stuff but I don't let them near ssh. But then, they don't know about file modes either! ;)

**Comment by robconery** [comment]
Why wouldn't you let them near SSH? I'm confused.

**Comment by rosswintle** [comment]
Because, generally, they're using the terminal to follow copy-and-pasted instructions for things like modifying their local host file or flushing their DNS cache. Competent enough to do some managing of their own device under instruction.  But not competent to be let loose on remote servers.

Don't worry about it. They're not the kind of people who will read your book! :)

**Comment by robconery** [comment]
Hmmm. I hate to admit it but I've completely lost wherever this thread was going... but that's OK. As I mention I'm going to add a think on SSH, how it works, what it does etc. Hopefully this will address the readers you mention who won't read this book 😄

**Comment by rosswintle** [comment]
I think I've totally confused myself too. Thanks though! 😃
