### ISSUE TITLE
typo: Lambda Calculus javascript example results is undefined

### ISSUE THREAD

**Issue by luddd3** [robconery/feedback#3]
In Lambda Calculus -> The Basics of Lambda Calculus

The javascript example is a little bit wrong. The result of the following snippet is actually "The value is undefined" due to the missing 5 in the function invocation and a missing return statement.

``` javascript
var showMessage = function(val){
    console.log("The value is: " + val)
};
//pass a function as a value, invoking it
showMessage(function(x){x * x}()); //The value is 25
```

Also the comment is somewhat misleading, as the function is never passed to showMessage. I suppose that you have deliberately avoided using ES6?

I would have written the example using ES6 as this:

``` javascript
'use strict'
let square = x => x * x
console.log("The value is: " + square(5))
```

**Comment by robconery** [comment]
Oh man - nice catch. This was one of those sections I had earmarked as _run this_... crap. Thank you!

**Comment by robconery** [comment]
Can't find your name/email... what is? Also: fixed. I used your code snip and wanted to give you credit.

**Comment by luddd3** [comment]
Haha, I have a habit of locking down all my accounts as much as possible

**removed**

**Comment by robconery** [comment]
Me too :). Thanks so much for your help _ I bought your copy for you and if we keep going I’ll happily pay more for your time … your help is so very appreciated!

**Comment by robconery** [comment]
Edit your comment if you like now... I have it :) and I fixed this with your code...
