### ISSUE TITLE
"Who, What, Where" drawing could be dangerous

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#30]
Given that the Who What Where chapter assumes people don't know about file permissions and /dev/null, which is explained later, is it wise to have a drawing on the first page of a computer showing a potentially very destructive command? (Well, actually, I don't think this command does anything, but I'm not about to test it!)

I'm not saying your readers are stupid. But if they are, or if they don't get the sarcasm (which is possible with an international audience), do you want them running this, or trying something similar, without being informed?

**Comment by wconrad** [comment]
The command is harmless as given because the target `/dev/null` is not a directory, so mv will reject the command.  If someone removes or changes the target, then the command could do some damage.

**Comment by robconery** [comment]
I have to, at some point, rely on the reader to have _some_ common sense. If they don't then there's nothing I can do in any case.
