### ISSUE TITLE
Root and sudo: directory permissions need explaining

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#31]
In the section Root and Sudo, you should probably explain that execute permissions on a directory allows you to enter the directory. Whereas execute permissions on a file let you execute/run the file.

I didn't really set out to provide so much feedback. I hope it's useful. I don't want to be an asshole. I'm a nice person really and I think this is a really important book. Let me know if this feedback is useful or not. I'll shut up if you want me to.

**Comment by robconery** [comment]
Sorry for the late delay! NO NO NO you are not an asshole THANK YOU! I love that you're helping... I really do thank you so much!

**Comment by robconery** [comment]
Closing for now as this is getting reworked.
