### ISSUE TITLE
Errors in "Who, What, Where"

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#33]
A couple of minor details from Page 42:

> As it turns out, this is the /bin directory, owned by the system god, root .

The last thing we were looking at was actually a directory we made called "secret" so this is a bit confusing. I suspect this refers to "using the first row in the example above to illustrate" from the previous page, but you added some content in between

> Most of the core applications and programs are in there ("cp", "ls", "cd", etc),

cd is a shell built-in command and will not be found in /bin

**Comment by robconery** [comment]
Thank you! Fixed :)
