### ISSUE TITLE
Clarify Unix, Linux, OS X/macOS

### ISSUE THREAD

**Issue by juri** [robconery/feedback#36]
I'm not too far in the book yet, so maybe you address this later on, but this was something that I noticed in the Linux bits:

The distinctions between Unix, Linux and OS X/macOS are left pretty unclear. It's hardly the most important thing ever, but still, would be nice to get it mostly right. Now the text makes it sound like Unix was something historical, Linux is the thing and OS X is/contains Linux. A more accurate description would be, ignoring certification and trademarks, that Unix is a [family](http://core0.staticworld.net/images/idge/imported/article/ctw/2009/06/04/unix_chart_775-100397147-orig.jpg) of operating systems, of which both Linux and OS X are members. OS X does ship with some GNU tools, but the userland is mostly BSD and the kernel is something completely different (actually [a close relative](https://en.wikipedia.org/wiki/Mach_%28kernel%29) of GNU Project's own kernel, Hurd.)

**Comment by robconery** [comment]
Great point - I'm redoing a lot of the Linux bits right now, so I'll probably add a fat blurb on exactly this - thanks!

**Comment by denmch** [comment]
I just started the book and came to say the same thing. I think it'd be a good idea to give a brief statement about the relationship between UNIX and Linux with reference to UNIX-like systems as a way to introduce a common catch-all term, like *nix, and use that throughout. Or if your references lean toward Mac, acknowledge Linux as UNIX-like and refer to UNIX throughout. A third option is to simply refer to the command line, allowing for references to each as appropriate.

**Comment by robconery** [comment]
Righto - I tried to do that with the history section but I guess it fell short. How much expansion do you think is required?

**Comment by robconery** [comment]
OK, I added a fat blurb on this. Thoughts?

https://gist.github.com/robconery/b5b08cc1af91aad8541cbe01cd40dbf7

**Comment by juri** [comment]
- I'd tweak the language of 
  
  > It is closed-source and still widely in use today
  
  If my understanding is correct BSD has some shared history with the AT&T code base as does Solaris (via both BSD and SVR4), and I'm sure AIX and HP-UX do too, but still, that might be a bit misleading in that the versions that are being used have been forked since the 80s.
- OS X, not OSX. Also might be worth it to switch to calling it macOS, given that 10.12 will probably be out with the new name in a few weeks.
- You'll get complaints about not mentioning that Ubuntu is a Debian derivative, but I think it's fine to not include every bit of history.
- I'd add a sentence mentioning Red Hat and SUSE, the other two big commercial offerings in the Linux distro space.

**Comment by robconery** [comment]
Perfect - thanks!

**Comment by kaler** [comment]
I wouldn't call the first section Linux.  I'd call it "The Command Line" or "The Shell".  And then focus on what the command line is, what it is for, what you can do.
https://en.wikipedia.org/wiki/Shell_(computing)

And then in a separate section go into defining the difference between kernel, operating system, shell, Unix, Linux, GNU/Linux, BSD, and Mac OSX, etc.
https://www.gnu.org/gnu/why-gnu-linux.en.html

I think you're muddling two different topics here.

**Comment by robconery** [comment]
I'm redoing the whole thing...

**Comment by aa-altieri** [comment]
A few more thoughts on OS X/MacOS.  

First, I'd keep the references to OS X, but maybe add a note that the name is changing to MacOS.  I wouldn't REMOVE the name "OS X."

Also, looking at your blurb that was linked above, I can't agree with what you wrote.  Strictly speaking, OS X is based on NextStep, which is based on the Mach kernel, which is based on BSD.  So OS X is more of a grand- (or even a GREAT grand-) child to BSD.  And I do think that's a bit important as it's not true to say "When people refer to Unix systems they are sometimes referring to Unix-like systems, which usually means Linux."  Actually, the most popular unix-like OS is not Linux at all.  

Linux is the name most people HEAR when thinking about unix-like stuff.  But that's only because they don't realize the relation to unix that OS X has.

Either way, remember:  Unix is the answer.  But only if you asked the question VERY carefully. ;-)

**Comment by pjbirch** [comment]
In the same vain, on p67 of the 002 pdf, you state that "if you're on a Mac, you already have it" (meaning Linux).  Suggest that this is changed to "a unix-derivative" or similar?

**Comment by robconery** [comment]
I'm removing all discussion of Linux history.
