### ISSUE TITLE
Docker Screenshot

### ISSUE THREAD

**Issue by rawkode** [robconery/feedback#37]
You advise that the user should select the "Recommended" Docker Image, but unfortunately in your screenshot that recommended image is a deprecated Ubuntu upstart image. Ubuntu doesn't even use upstart anymore, so I'd maybe take another screenshot

**Comment by robconery** [comment]
Thanks David - I think I might remove the Docker section out of there entirely; it's a bit tangential and it's probably much easier to recommend spinning up an AWS/Ubuntu free image or DigitalOcean.
