### ISSUE TITLE
Linux File Permissions

### ISSUE THREAD

**Issue by rawkode** [robconery/feedback#38]
"Initially the group owner in inherited from the containing directory. So if I create a new directory within my home directory, I will own it and whatever group owns my home directory will own my new directory as well"

This is incorrect. The owner of the file will always be the creator of the file, unless modified. The group will be the users group, or simply "users" if there isn't one.

**Comment by robconery** [comment]
The ownership stuff I'm pretty clear on - the group ownership, however, I _thought_ I had correct, given:
- Experimentation. I tested this out on a Linux box and my local Mac. If a directory was owned by Wheel, for instance, any new directory was owned by Wheel. Same with staff. On Linux this was the same effect - if I was `root` and created a directory belonging to `some_group`, the new directory would also belong to `some_group`
- Reading examples. I've combed through so many different forums and Linux docs - mostly they tell you how to `chgrp` but don't mention defaults.

As with most things, I could have stared at this for far too long and muddled it completely. Would you mind pointing me at the source for your thoughts? Or, better yet, would you mind providing an example?

**Comment by rawkode** [comment]
What you explain is possible, with the setgid and setuid bits set. Though this isn't default behaviour :+1:

**Comment by rawkode** [comment]
https://www.gnu.org/software/coreutils/manual/html_node/Directory-Setuid-and-Setgid.html

**Comment by robconery** [comment]
Thanks again - I've read about Setgid/Setuid and how you can alter the defaults; What I've seen, however, seems to suggest the default group owner is inherited. I'll keep looking for the default behavior...

**Comment by robconery** [comment]
OK I just confirmed this - crap I had it backwards. Gah! The funny thing is this (the default group owner) was _always_ the group of the user that created the directory... and then I read and read and (evidently misread) ... and did the wrong thing.

Too much reading - will correct! Thanks again.

**Comment by ghost** [comment]
Also it should probably state that the members of a group can read and execute, not the group owner.

**Comment by robconery** [comment]
I'm removing these parts...
