### ISSUE TITLE
Who, What Where: Setting a Default Editor

### ISSUE THREAD

**Issue by rawkode** [robconery/feedback#39]
You suggest vim, which is great. However, you say that if it's not installed, it can be installed with `apt`

Maybe worth adding an info box to clarify that  `apt` is the package manager for Debian based distributions and that RedHat based would use `dnf` and Arch based `pacman`

**Comment by robconery** [comment]
Will do! Thanks again :).

**Comment by kamranayub** [comment]
On this note, I had to actually execute

```
sudo update-alternatives --config editor
```

Otherwise I got:

```
update-alternatives: error: error creating symbolic link `/etc/alternatives/editor.dpkg-tmp': Permission denied
```

**edit:** I wonder if it's because the book assumed I was starting as root whereas I had a user already (not root).

**Comment by robconery** [comment]
I'm removing this walkthrough I think...
