### ISSUE TITLE
feedback: Big-O Notation, consistent usage of notation

### ISSUE THREAD

**Issue by luddd3** [robconery/feedback#4]
I love your cat drawings!

Sometimes the numbering uses lowercase n and uppercase N.

The readability could benefit from consistent usage of O(n) and O(N). I suggest that you stick with a lowercase _n_ and make it italic in the text in order to make it more readable. That way you make it easy on the eyes both in the math, e.g. O(n log n), and in the text.

**Comment by robconery** [comment]
Totally agree. Fixing...

**Comment by robconery** [comment]
Done!
