### ISSUE TITLE
Who, What Where: Installing Software

### ISSUE THREAD

**Issue by rawkode** [robconery/feedback#42]
"but people typically use Aptiude or Yum. I'm working with Ubuntu, so by default I use Aptitude"
1. Aptitude is actually a different bit of software, a ncurses based package manger that wraps apt. The Debian package manager is simply called "apt": https://wiki.debian.org/Apt
2. Yum is the old RedHat package manager, to stay current I'd update to `dnf` https://en.wikipedia.org/wiki/DNF_(software)

**Comment by robconery** [comment]
I'm going to remove this entire chapter.
