### ISSUE TITLE
Suggestions: The Essential Ten Commands

### ISSUE THREAD

**Issue by rosswintle** [robconery/feedback#47]
> `rm`: deletes a file or directory

Should you contrast `rmdir` to avoid confusion?

> `cat`: show the contents of a file

Should you suggest `more` or `less` as paged alternatives?

> `sudo`: turn yourself into `root`...

`sudo` runs a single command as root; `su` turns you into root

Either fix the command or the description

**Comment by robconery** [comment]
Great distinction and yes I'll add those suggestions.

**Comment by ardacetinkaya** [comment]
Also I think chmod is one of the essential commands. In the part that you mention about file/folder permissions, you can add it a brief info.

**Comment by robconery** [comment]
I removed the Linux bits for now. Might come back in a later edition.
