### ISSUE TITLE
Suggestion: Use epubcheck as validation tool for your EPUB file

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#48]
Hi, first of all, congratulations for your great work, I read today about your book and I bought it immediately :)

You could validate your EPUB file using [epubcheck](https://github.com/IDPF/epubcheck), it's great to catch some errors like, missing `alt` attribute in images (good for screen readers for example) , or referenced resources that could be not be found in the EPUB, among others.

This is the current log for the [imposter_pre_002.epub](https://github.com/imposters-handbook/feedback/files/429296/epubcheck.txt) document.

**Comment by robconery** [comment]
I use Calibre, which is validating with epub 3. The output here is for epub 2, I believe.

**Comment by milmazz** [comment]
@robconery Your `META-INF/container.xml` points to `content.opf`, in that file, you'll see that the EPUB version is _2_. So, I think that's why `epubcheck` apply the rules against EPUB 2. 

```
$ cat META-INF/container.xml
<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
   <rootfiles>
      <rootfile full-path="content.opf" media-type="application/oebps-package+xml"/>

   </rootfiles>
</container>

$ grep -E "^<package" content.opf
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="uuid_id" version="2.0">
```

HTH

**Comment by milmazz** [comment]
More information about this, the [Package Document definition](http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-package-elem) specifies the following:

> _Element Name_
> **package**
> 
> _Usage_
> The package element is the root element of the Package Document.
> 
> _Attributes_
> **version [required]**
> Specifies the EPUB specification version to which the Publication conforms.
> 
> The attribute must have the value 3.0 to indicate compliance with this version of the specification.

**Comment by robconery** [comment]
Wow - yuck. That would be Gitbook :(. Hmmm.
