### ISSUE TITLE
No instructions to install zsh, only ohmyzsh?

### ISSUE THREAD

**Issue by kamranayub** [robconery/feedback#49]
Maybe I'm missing something (loving the book so far) but I am at the "Task: Oh My Zsh!" chapter and I tried executing the command but it says I don't have zsh installed. I scrolled up in the book but nowhere does it mention how to install zsh, leaving me sad I can't participate in the cool kid crowd.

I'm sure I can Google how to install zsh (which I will do now) but I think it makes sense to talk about how to get z shell before installing ohmyzsh.

**Comment by robconery** [comment]
You're not missing something - I need to add that in thanks!

**Comment by milmazz** [comment]
I think is worth to mention the requisites for _Oh My Zsh_, such as: `git` and `zsh`. Also, I think you should mention that the installer script verifies that.

**Comment by robconery** [comment]
Yep - thanks! This is fixed...

**Comment by turp** [comment]
I'm a little late chiming in. I just noticed the same issue: zsh wasn't installed. My first thought was that you should tell me how to install it. But, upon further consideration, you've already taught me how to install other things using apt-get. 

Maybe frame this as a challenge for the reader: "Before we can install Oh My Zsh, we need to install zsh and git. Based on what you've learned so far about installing applications using apt-get, try it on your own" 

Love the book so far. Thanks!
