### ISSUE TITLE
Not really true that there was no open source OS before Linux

### ISSUE THREAD

**Issue by gramster** [robconery/feedback#51]
There were no GPL ones. But there was Andrew Tannenbaum's Minix (which I believe was a big inspiration to Torvalds) and more importantly there was BSD. And BSD would most likely have been the winner if it didn't get embroiled in a lawsuit with AT&T in the early days of Linux; that lawsuit stalled BSD for a while during which time Linux had the space to grow. But BSD was considerably more mature up to that point.

https://en.wikipedia.org/wiki/Berkeley_Software_Distribution#Net.2F2_and_legal_troubles

**Comment by gramster** [comment]
Also worth noting that BSD was much more friendly to commercial software as it had a less restrictive license than GPL. Back in the 90's I had a startup building internet firewalls and VPN appliances on FreeBSD for this very reason.

**Comment by robconery** [comment]
Thanks - I'm removing all discussion about Linux history.
