### ISSUE TITLE
Suggestion From a Linux User: Reorder Sections

### ISSUE THREAD

**Issue by zoffixznet** [robconery/feedback#52]
It's hard to give harsh feedback, and I hope you don't interpret it as ill-intent... I'm sharing because you asked.

> This book is pre-release, [...] I'm also hoping for a little help, if you don't mind. [...] If you find something that could use some help, I'd love to hear about it. 

I'm a self-taught programmer who have used Linux for over a decade and a half and if you ignore my playing videogames on a Windows PC, I've used it far longer than I've used a Windows machine.

The title of the book and its two forewords got me excited! Finally! I was about to learn the **Comp. Sci. stuff** I've been missing out for the 15 odd years I've been writing code. Yey! Awesome! And then...

... I got utter basics, such as `cd` (which Windows also has) and `ls`, shown and explained to me like I've never seen a computer before. Then, there's a whole section on `visudo` that anyone who doesn't already know how to use can do [a 1-second google search and find the answer](http://askubuntu.com/a/124200). Then, the book goes into how to choose themes on the Terminal.app, which has nothing to do with programming, self-taught or college-educated, and it's at this point I started to lean in on the PageDown button.

Right now, I've gotten as far as page 68 (!) and I've literally not learned a single thing I—a lazy, lousy, self-taught programmer—didn't already know. I'm a bit bummed out and annoyed and definitely lost all of the excitement I felt at the start of  the book. I'm now looking at the table of contents and I see I've made it just through the first half of the Linux section, and I see there's setting up a webserver on the menu, which is boring and many self-taught **web developers** done that a thousand times too.

It's the `Comp Sci, Baby` section that starts to look interesting to me. Big-O, P = NP, Binary Trees... it's _this_ stuff I've heard passed around and never knew exactly what they were.

So my feelings you asked to share are this: 
### The Radical

Burn the Linux section with fire. Cut it out of the book. You'll lose 89 pages of content, which sounds like throwing a lot of your work into the bin, but it will trim your book to the less-intimidating 374 pages and keep it much more focused on the topic. If a self-taught **programmer** doesn't
already know how to set up a web server, chances are it's because they aren't doing web work, and your book will just distract them by trying to show how.
### The Less-Radical

If you can't part with that section entirely, at least move it all the way to the end of the book. Call it a 'Bonus' section or something and maybe add Windows stuff to it too. As an experienced developer who uses Linux, I can tell you it's pretty embarrassing when you can't figure out how to edit a file on Windows from command line... so perhaps add a Windows Basics section to go together with Linux, because there will be times when a programmer can't choose what OS to deploy to or they have to debug code on a Windows machine and such stuff can be useful.

My two cents.

Cheers,
ZZ

**Comment by robconery** [comment]
Thanks :) - as I mention I wrote the book for me and a lot of people I know who _know nothing_ about Linux. Your perspective is very subjective - a lot of people learning to program these days do so on Windows or a Mac - never cracking under the shell.

**Comment by robconery** [comment]
Also - I don't mind refunding at all if you don't get value from the book :). I do appreciate your feedback ... radical or otherwise :).

**Comment by zoffixznet** [comment]
No, no. No refunds. I'm sure I will love the Comp Sci parts :)

**Comment by robconery** [comment]
Groovy - keep me posted! Also - I have thought about moving that chapter back a bit - maybe I will. To me the Comp Sci stuff is the strength, it also fits in a timeline way. I'm going to reopen for now...

**Comment by robconery** [comment]
Yeah... yeah I'm going to do this. Thanks for the prod!

**Comment by robconery** [comment]
Done and done... closing.

**Comment by jaridmargolin** [comment]
Hi Rob. My intentions here aren't to spam but I wanted to voice my agreeance with @zoffixznet. Specifically the following two quotes resinated with me:

> The title of the book and its two forewords got me excited! Finally! I was about to learn the Comp. Sci. stuff I've been missing out for the 15 odd years I've been writing code. Yey! Awesome! And then...
> 
> I'm a bit bummed out and annoyed and definitely lost all of the excitement I felt at the start of the book.

While I don't argue the importance, or usefulness of the linux section, I personally do not believe it fits with the theme of this book. Perhaps it can be pulled out, expanded, and spun up as book specific for developers transitioning to linux.

All work you have done is greatly appreciated. I am only commenting here so that you have an honest depiction of how other developers may be receiving this book.

**Comment by robconery** [comment]
No problem - it's a tight rope between "CS stuff" and "gaps in general developer knowledge". Either way - I've found (overwhelmingly) that people really dig the CS stuff so... out comes Linux! I'm also adding new sections on Math and Computation as well as Probability - and I'm also adding 75% more chapters to the algorithms chapter.

And out comes Linux :). I _will_ be pushing a fixed up, "interim" version in the next day or so but in a month - it'll be like a new book in some ways :).
