### ISSUE TITLE
Introduction: his/her

### ISSUE THREAD

**Issue by adamipc** [robconery/feedback#54]
I would suggest using the singular "their" for this since you don't know this persons gender and even though its likely they identify as male or female, the way to be most inclusive is to allow for the situation where they might identify as non-binary.

**Comment by robconery** [comment]
I don't know what you're referring to...

**Comment by adamipc** [comment]
Page 5 in imposter_pre_002.pdf: "I am using a screen shot because I don't know who the author is and I wanted to capture his/her exact words as closely as possible."

**Comment by robconery** [comment]
Ah - I should have caught that as my use of "his/her" was intentional. I typically use "their" when discussing an unknown person - but in this sense we're dealing with a powerful comment; the "soul" of the book if you will. I honestly think most men will think a man wrote this.

So I used the term "his/her" consciously here. I want men to stop a moment and ponder, at some level of thinking, whether they thought M was a man.

I'm inclined to leave it as is.

**Comment by adamipc** [comment]
I understand your intention. I'd appreciate it if you could consider an alternative interpretation. Let's examine how this reads to different people:
1. A man reading this may ponder, but may also just pass it by thinking that you don't know who the person is, so you're doing the obvious thing of not picking a gender.
2. A woman reading this may do the same, maybe there's a chance they will also appreciate you didn't just say "his".
3. Someone who does not identify themselves as either him or her reads it, and like most everything else in the society around them, this sentence has made the choice to erase their existence as a possibility. 

Using "their" also has the added benefit for men and women reading it to get more used to the singular they/them/their in their daily reading, normalizing the idea that gender is not a binary and there are many people who choose to (and should have the right to) exist outside of the binary that society has placed on all of us for so long. Slowly, a grain of sand at a time, every time we use they/them/their instead of he/she, him/her, his/her we shift this perception and make the world safer for people who have increased rates of suicide and violence done to them.

Sorry for going on so long, I just wanted to make the best argument I can for this change because I care and I understand that not everyone thinks about these sorts of things reading a stray "his/her", but it really does make a difference to some people.

**Comment by robconery** [comment]
I appreciate that you care about this - as I mention I wrote that sentence intentionally, as I did throughout the book when I use "her" for boss, CEO, etc. This was my choice to do what I wanted to do with it. I respect your ideas about non-binary folks, but we can only cram so many agendas into one book.

**Comment by robconery** [comment]
Locking this thread to avoid side conversations - please do email me if you want to continue. I don't mind talking about it more, just not here.
