### ISSUE TITLE
Problems in ebook with dark bg

### ISSUE THREAD

**Issue by cassiozen** [robconery/feedback#57]
Reading the epub on iBooks, some texts are unreadable (specially images, which do have a white BG that fills only part of the images).

<img width="596" alt="screenshot 2016-08-23 09 32 17" src="https://cloud.githubusercontent.com/assets/33676/17891964/3691bdbe-6915-11e6-8dad-fa306db6de48.png">

**Comment by robconery** [comment]
Looks like you changed the font a bit?

**Comment by zoffixznet** [comment]
On the same topic, I found the quoted portions a bit too light on white background, making them hard to read, especially when they're large. The light gray they use [fails the WCAG 2.0 accessibility guidelines](http://leaverou.github.io/contrast-ratio/#%23A1A1A1-on-white) too.

![png](https://cloud.githubusercontent.com/assets/5747918/17907162/7d050f52-6948-11e6-8017-15a6b8980cb4.png)

**Comment by robconery** [comment]
Redoing the formatting with a different program to address this.
