### ISSUE TITLE
Suggestion: Windows

### ISSUE THREAD

**Issue by cdhunt** [robconery/feedback#59]
Yes, roll your eyes, but it is a popular platform and people do write software for it.

I think a chapter similar to the Linux chapter would be useful and appropriate. 
- Tools
- The .Nets
- Powershell
- Commands you should know
- MSBuild
- Task: A new Jekyll Post with Powershell
- Task: Set up a Web Server with Desired State Configuration
- Task: Set up Windows Linux Subsystem
- Task: Cross the streams - Run Python from Powershell on Linux on Windows

**Comment by robconery** [comment]
No eye rolls, promise - I just had this discussion with someone who asked me "why did you include Linux?" - I think my response would fit here as well.

The goal of this book is to provide for people without a CS degree. Typically, CS grads have exposure to Linux, scripting, etc as well as core things like comp. theory.

Self-taught developers (if I can use a somewhat broad brush here) typically don't "crack the shell" and work through the Windows GUI or the Mac. Some of course do (which you're probably firing up to tell me right now). Either way - the self-taught people are my audience. I find that Windows devs make up a _gigantic_ number of those developers.

I appreciate where you're coming from, but it's not something I want to add.

**Comment by cdhunt** [comment]
![Fair enough](http://vignette2.wikia.nocookie.net/glee/images/0/09/Okay_fair_enough_I_can_deal_with_that_thanks_smile_doctor_who_matt_smith.gif/revision/latest?cb=20140831231858)

**Comment by robconery** [comment]
Well I thought I gave you a reasonable reply - if you disagree by all means share. Dropping gifs is a bit disrespectful of both our time isn't it?

**Comment by cdhunt** [comment]
Sorry, meant to be light-hearted, not disrespectful. I respect your decision to control the scope of the book.

**Comment by robconery** [comment]
Totally understand - and I figured as much :). Just hoping to hear your point of view rather than a gif :).
