### ISSUE TITLE
Shell Scripts

### ISSUE THREAD

**Issue by allykzam** [robconery/feedback#60]
At the beginning of the Shell Scripts section:

> Shell scripts are little programs that your OS will run for you.

It's a little bit nitpicky, but shell scripts are run by the shell they're targeted for, not the OS? Rather than `programming your computer to do your bidding`, I usually explain them as being like a macro (assuming the person I'm talking to knows what macros are); when you go to run the script, it's really just running a long list of individual commands as if you had manually entered them really really quickly.

**Comment by robconery** [comment]
Yep - great point thank you!

**Comment by robconery** [comment]
Fixed!
