### ISSUE TITLE
Brief primer for Vim?

### ISSUE THREAD

**Issue by jmurty** [robconery/feedback#61]
Hi, I'm enjoying your book (version pre 0.0.2) and as a Vim user myself I'm happy you recommend this editor. However, while the _can't quit Vim_ jokes are old and unfunny, there is a kernel of truth in that it is a difficult editor to get to grips with initially.

I think it might be helpful for readers new to Vim to give a brief primer to give some context for the fairly arcane editing command examples that follow. Such a primer could include things like:
- explain Vim is modal: you are either navigating a document (with keys other than just the usual arrow keys); or you are editing the document to insert or change text
- list the most useful commands, in the context of file edits you are about to demonstrate: `i` to start inserting text, `Esc` to return to navigation mode, `:w[rite]` to save, `:q[uit]` to quit, `jklh` as alternatives to arrow keys, `/` to search. You mention most of these as you work through the examples but having them up front might be helpful
- mention why you prefer to use Vim, so readers feel motivated to get over any strangeness or annoyance they might feel. Maybe describe editing motions a little: at least, that's one of my favourite things and is fairly unique to Vim
- point curious readers to the inbuilt `:help` command, and the `vimtutor` program to learn more
- but also mention an easier alternative – maybe nano, or whatever else isn't too terrible and has more standard behaviour and always-on-screen shortcut hints – so readers struggling with Vim don't get stuck.

**Comment by robconery** [comment]
Yeah I was thinking about adding this. Good idea ...

**Comment by stereobooster** [comment]
> but also mention an easier alternative – maybe nano

It is not just "easier" alternative. It is different class editor. Vim is "modes" editor. Nano is "[no modes](http://www.nomodes.com/Larry_Tesler_Consulting/Home.html)" editor.

![](https://itsthedatastupid.files.wordpress.com/2010/05/nomodes.jpg)

[slap](https://github.com/slap-editor/slap) is example of advanced "no modes" terminal editor.

**UPD**. One more note before anyone will dive into selecting perfect text editor: see [this video](https://www.youtube.com/watch?v=dIjKJjzRX_E&index=1&list=PL0zVEGEvSaeH21VDycWYNWU7VKUA-xLzg)
