### ISSUE TITLE
Mention executable shell scripts

### ISSUE THREAD

**Issue by jmurty** [robconery/feedback#62]
The shell script examples at the start of the book tend to use functions heavily, which for me is an unusual practice.

Wrapping shell script behaviour in functions can be useful because the functions can be loaded into the shell and will always be readily available.

However I think it would be worthwhile to mention the more common (?) approach of starting shell scripts with a hash-bang and making them executable. You need to type the path to the file for these scripts, but they are easier to share because they can live in the code repositories to which they apply and there's no risk of function name clashes. You still have access to all the `$1` variables with this approach, though you claim otherwise in "Start with a Function" where you say functions are necessary to use variables.

As an example, the "new_post" script could also be written to a _new_post.sh_ file with:
- `#!/bin/bash` on the first line, to explicitly specify it as a bash script (or zsh if you want)
- make it executable with `chmod u+x new_posts.sh`, so you can invoke `new_posts.sh` to run it instead of `sh new_posts.sh`
- no need for the `new_post()` function wrapper around the remainder of the script.

Maybe all this ceremony to make the shell scripts directly runnable is unnecessary overhead for your examples, but I think it's worth mentioning the alternate approach.

**Comment by robconery** [comment]
Cheers - good stuff thanks!

**Comment by ScottESanDiego** [comment]
Agreed - the paradigm that I use and see in the wild is exactly what the OP mentioned - shebang shell scripts and call them directly as if they are standalone programs rather than extending the shell with functions.  +1 for the recommendation.

**Comment by robconery** [comment]
I removed this entire section...
