### ISSUE TITLE
tr unicode

### ISSUE THREAD

**Issue by juri** [robconery/feedback#63]
On page 129 of 0.0.2 the sed/tr pipe doesn't maybe quite handle Unicode as you'd like it to — the `A-Z a-z` bit leaves non-ASCII capitalized letters untouched.

This can be fixed at least on OS X, with BSD tr, by using character classes. I don't have a Linux shell with GNU tools handy right now to check if it's the same there. And of course, this assumes you have your locale environment variables set up right to handle Unicode:

``` sh
echo "foo bÄr Zap quux" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr '[:upper:]' '[:lower:]'
```

This will output

> foo-bär-zap-quux

**Comment by robconery** [comment]
Interesting - given that the slug is for a URL is this a good idea?

**Comment by juri** [comment]
Oh yeah, that's an excellent point :-)

It's definitely a potential source of headache, however it's done. I _think_ it's safe to include UTF-8 encoded URLs in HTML5 documents these days, but if not, you can always use percent encoding. However, there's still the step of mapping the URL paths to files, whose names from the point of view of the file system are just byte sequences. It will probably work ok if you manage to consistently use UTF-8 always everywhere, as you should, but it's easy to break it by getting locale-specifying environment variables (`LC_CTYPE` etc) wrong. And that's the sort of thing where the defaults are often wrong and things might change when you upgrade something or ssh in from another computer or whatever.

However, it's doesn't help you to not do this change: if you keep the original `tr A-Z a-z`, the output string would be "foo-bÄr-zap-quux" so you're still facing the same problems. If you wanted to play safe, I think you should replace the `[:alnum:]` in the sed invocation with `A-Za-z0-9`, which would change the "Ä" to "-". Or you could just run your original command line in an ASCII locale, where `[:alnum:]` is probably equivalent to `A-Za-z0-9`. But if you decide to force ASCII slugs and some day wanted to write a post in Japanese, your slug would be something very close to "-----".

Or you could just punt the problem and state the constraints: it's an example, you're writing in English, you're not worried about the problem right now, and caveat emptor if you need non-ASCII characters.

**Comment by robconery** [comment]
I totally get your point but it doesn't work with the example - so for now I'm leaving it out.
