### ISSUE TITLE
Shell error output: zsh vs bash

### ISSUE THREAD

**Issue by juri** [robconery/feedback#64]
On page 129 of 0.0.2, you display a shell error and explain:

> ```
> $(echo -n $TITLE | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)
> zsh: command not found: a-little-brown-pig-by-rob-conery
> ```
> 
> We get an error. Bash thinks that we're trying to execute a literal string, which is the result of our subshell command!

You're getting the error from zsh, not bash. The language may be bash, but because you're sourcing the script from zsh, instead of executing the script as a subprocess as per #62, it's zsh that has opinions about the syntax.

**Comment by robconery** [comment]
Ah - great point! Thank you!
