### ISSUE TITLE
Binary search complexity O(log n), not O(n log n)

### ISSUE THREAD

**Issue by heintz** [robconery/feedback#68]
The explanation on p134 incorrectly implies that binary search has complexity O(n log n) "because I need to do the additional step, for each n item, of deciding which split to keep".  Deciding whether to recursively search the left or right half, however, is an O(1) operation.

The text in "Sorting the cats" on p135 needs to be updated once this is, as sorting is more complex than binary search.

**Comment by robconery** [comment]
Thanks - I goofed that one :).

**Comment by maebeale** [comment]
was wondering abt that one too. this makes way more sense.

**Comment by robconery** [comment]
Thanks this is fixed.
