### ISSUE TITLE
Suggestion: word change (dude) page 121

### ISSUE THREAD

**Issue by cvaneseltine** [robconery/feedback#71]
I suggest changing the word "dude", as it implies that your intended audience is male.

**Comment by robconery** [comment]
I'm wondering if you're aware of the context behind the phrase "Turn up the Pink Floyd dude"?

**Comment by shanselman** [comment]
Is this from a song?

**Comment by cvaneseltine** [comment]
If it's a pop culture reference, it went straight past me.

**Comment by robconery** [comment]
It's not an _exact_ reference, per se, I suppose you could call it an _allusion_ to Cheech and Chong. In the book I had just expounded on Plato, whether we live in a machine, whether god (in whatever flavor) is a machine... kind of a trippy discussion. Thus the reference... "turn up the Pink Floyd, dude".

To be honest I'm surprised more people aren't offended at my assertion that god is a machine. But I guess that might be coming next :).

EDIT: I'm removing it.

**Comment by robconery** [comment]
Never mind I'll remove the reference. I'm locking this issue to avoid a messy situation - but I hear you and understand that the context wasn't apparent and the word "dude" was off-putting.

**Comment by robconery** [comment]
Closing for now - this is fixed :).
