### ISSUE TITLE
Page 33 - Docker now uses Hyper-V by default

### ISSUE THREAD

**Issue by bill-long** [robconery/feedback#74]
```
Docker solves this for you (whether on Mac or PC) by installing a virtual machine driver: 
Virtual Box (which is free). You don't need to worry about this - Docker will manage it for you.
```

Docker no longer installs Virtual Box by default on Windows. It uses Hyper-V instead.

**Comment by gnufied** [comment]
Only if you are running Windows-10 Pro editions right?

**Comment by daenney** [comment]
Windows 10 Pro, Education and Enterprise editions come with built-in Hyper-V allowing users to create and run other operating systems on a virtual machine.

**Comment by robconery** [comment]
I tried to do it on Win 10 Pro and it installed Virtual Box - I wonder if I did something goofy in the setup?

**Comment by daenney** [comment]
Did you use the Docker for Windows release?

**Comment by robconery** [comment]
I did, yes. I'm removing the entire Docker para anyway...
