### ISSUE TITLE
Curl bashing scripts should be recommended with extreme caution

### ISSUE THREAD

**Issue by curiouslychase** [robconery/feedback#76]
It's important that the recommendation of installing oh my zsh through curl bash come with warnings, especially since this book is for people who may have holes in their knowledge. Tell them that this is a dangerous task if you don't know what the script is doing and that they should always read a script and understand it before following this procedure. Also, maybe talk about verifying the file is what's expected with a hash?

**Comment by robconery** [comment]
Crap! I have exactly this and somewhere along the lines the image was edited out that said _precisely_ what you suggest here. I’ll make sure it goes back in.

**Comment by robconery** [comment]
Here it is for reference...

**Comment by curiouslychase** [comment]
I just got there and was getting ready to close this. :smile: I still feel like that should probably be closer to the first curl statement, as oh-my-zsh, but I was so happy to get to this part and think, "phew, there we go."
