### ISSUE TITLE
Print edition?

### ISSUE THREAD

**Issue by jwmarshall** [robconery/feedback#77]
Do you have any plans to release a printed edition? I'd love to buy, and read, but I spend so much time reading screens that its more enjoyable to read something like this away from a computer. Thanks!

**Comment by andrey-p** [comment]
The FAQ further down in the [main page](https://bigmachine.io/imposter/) says:

> **Will there be a print version?**
> 
> That's my goal, yes. I want to be sure all the edits are made and, technically-speaking, the book is completed. If I do end up with a paper edition, I'll send out a note to the mailing list in late September, early October.

But yeah, not knowing whether a print version is definitely coming out is the one thing preventing me from pre-ordering this book.

Also: If it comes out, will the price be similar to the e-version?

**Comment by SteveKipp** [comment]
I bought the ebook/whatever version but I would definitely prefer the print version :frowning:

**Comment by jwmarshall** [comment]
I would be willing to pay more for a printed version. I have friends that have printed books with lulu.com and the end result is quite nice. I have 4-5 books printed from there.

**Comment by robconery** [comment]
My thinking on this is that I'll probably go with a print on demand service, which is expensive - but if I do that I'll hand out coupon codes to everyone that somehow balances the effort? I have not made up my mind - I'm just hyper focused on getting this thing buttoned up.

If you can hang tight for just a week or so - I'll look into the cost differences and how this can possibly work. Oh - yeah one major thing for me is that I need _color_ printing, thus the expense.

**Comment by robconery** [comment]
Closing as this is more of a question and I'd like to keep this list for issues.
