### ISSUE TITLE
Processor Architectures

### ISSUE THREAD

**Issue by allykzam** [robconery/feedback#78]
Three paragraphs into the `How a Compiler Works` chapter, a list of processor architectures is given &mdash; `x64, linux, darwin, etc` &mdash; but only the first of them is a processor architecture?

A few pages later under the `Getting the JITters` section of the same chapter, we're given a list of "processor level" byte-code options &mdash; `x86, darwin, linux, osx` &mdash; which makes the same conflation as before, but also lists an operating system (which happens to use one of the listed kernels).

**Comment by robconery** [comment]
Thanks - changed the first list to be "platforms" and went with Windows, Mac, Linux etc and just removed the second reference.
