### ISSUE TITLE
MSIL JIT Compilation

### ISSUE THREAD

**Issue by allykzam** [robconery/feedback#79]
Under the `Intermediate Language Output` section:

> When a C# program is run for the first time, the IL is recompiled down to native machine code, which runs quite fast.

Except that normal .NET applications (ignoring `ngen.exe` and the upcoming `.NET Native` as both are opt-in) have to go through JIT compilation _every_ time they're run, not just the first time. Given the gradual compilation as code is needed, it's not entirely dissimilar to the point made later about JavaScript, `...compile any script files referenced on a page, and will hold the compiled code in memory...`.

**Comment by robconery** [comment]
Keep it coming! I love it all - checking on what you’re asserting here.

**Comment by allykzam** [comment]
The best link I can think to give is [this StackOverflow answer](http://stackoverflow.com/a/1255832) from Jon Skeet, because if Jon Skeet and the .NET Framework disagree, it's the framework that is wrong. 😉

However, perhaps more usefully, if you want to open the Performance Monitor, there are some [performance counters](https://msdn.microsoft.com/en-us/library/w8f5kw2e%28v=vs.110%29.aspx#jit) you can watch as new parts of an application are used; the `# of Methods JITted` counter in particular is pretty fun to watch.

**Comment by robconery** [comment]
Funny you should mention Skeet - his email appeared just before yours (I forwarded this issue to him):

> That the code is JIT-compiled every time? Absolutely, normally. Note that it's not like the whole application is compiled each time though - it's usually done at a per-type or per-member level, so if you don't use a particular class or a particular method, that code need never be JITted. (The precise details of granularity vary by CLR.)
> 
> Jon

**Comment by robconery** [comment]
Fixed and thanks!
