### ISSUE TITLE
Typo: "effect" should be "affect".

### ISSUE THREAD

**Issue by JoshuaCarmody** [robconery/feedback#8]
In the chapter "Linux: Who, What, Where?", I believe there is a typo in the following sentence:

> /opt: optional software goes in here that, typically, doesn't effect the operation of the machine. If it's not in the root, it's typically in the /var directory.

I believe this should be "doesn't _affect_ the operation". In most cases, "effect" is a noun and "affect" is a verb. The only time "effect" is used as a verb is when it is used to mean "brought about a change/situation". For example: "The iPhone effected a big shift in the software industry".

**Comment by robconery** [comment]
Yep - thanks! Fixed...
