### ISSUE TITLE
Suggestion: Add info on sort stability

### ISSUE THREAD

**Issue by jspencer** [robconery/feedback#80]
As a self-taught developer, one knowledge gap I ran into on the job was that of sort stability.

Why is my sorted list changing order slightly on every refresh?
A co-worker pointed out to me that the quicksort in the environment we were using was not a stable sort, so items that compared as equal would be sorted arbitrarily causing them to jump around on every change. I think I ended up adding a merge sort implementation to fix it.

(I've seen what appears to be a bug like this in the inventory in the game Skyrim.)

**Comment by robconery** [comment]
Interesting - thanks. I'll add a blurb about this :).
