### ISSUE TITLE
Page 29 typo, "...protected from everything other process."

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#82]
On PDF page 29, something went wrong here: "...     the memory  in  which   it  executes    is  protected   from    everything  other   process."

**Comment by wconrad** [comment]
This appears to be a duplicate of https://github.com/imposters-handbook/feedback/issues/73 .  My PDF copy has the error on page 29; the creator of that issue saw it on page 30.

**Comment by robconery** [comment]
Fixed thanks!
