### ISSUE TITLE
P vs. NP

### ISSUE THREAD

**Issue by racko** [robconery/feedback#83]
> [...] A number of NP-Complete problems can **likely** be solved if we crack the Boolean satisfiability problem.

They can **provably** be cracked if we crack the Boolean satisfiability problem. NP-Complete will not only unwind itself in short order, all problems in NP will be cracked by definition.

> If NP-Complete problems get resolved, it's likely (though nobody knows for sure) that we'll crack _every_ NP problem.

Every NP problem would be cracked by definition. There is no uncertainty about that. "A decision problem C is NP-complete if: 1. [...] 2. Every problem in NP is reducible to C in polynomial time." ([NP-completeness](https://en.wikipedia.org/wiki/NP-completeness)). This means that by definition, if we have a polynomial time algorithm for any NP-complete problem, then we can use it to solve any problem in NP in polynomial time, too. [The Cook-Levin theorem](https://en.wikipedia.org/wiki/Cook%E2%80%93Levin_theorem) shows that you can use an algorithm for the Boolean satisfiability problem to solve any problem in NP with only polynomial time overhead, so if the algorithm for the Boolean satisfiability problem is polynomial time itself, the total time would be polynomial as well and the NP problem could be solved in polynomial time, thus P=NP. 

> The definition states that NP-Hard problems have to be _at least_ as hard as the hardest problems considered to be in NP, but they don't actually have to be in NP ... which means they cover things that can't even be decided. [...] Turing proved that it [the halting problem] and showed that it was undecidable. That "undecidable" part is what makes this problem NP-Hard.

~~The halting problem is not NP-hard. For it to be NP-hard, it would need to be NP, for which in turn it would need to be a decidable: 'Informally, NP is the set of all decision problems for which the instances where the answer is "yes" have efficiently verifiable proofs.' ([NP_(complexity)](https://en.wikipedia.org/wiki/NP_%28complexity%29)). The halting problem is a decision problem, for which there are instances where you cannot prove the answer to be either "yes" or "no".~~ [The halting problem is NP-hard](http://stackoverflow.com/questions/6990683/proof-that-the-halting-problem-is-np-hard). I correctly, but irrelevantly, explained why it is not NP-complete :(

Irrelevant: (You also cannot use the halting problem in the way I described above that you can use the Boolean satisfiability problem to solve NP problems: The statement would be "you can use an algorithm for the halting problem to solve any problem in NP with only polynomial time overhead". But since there provably is no algorithm for the halting problem (that's what Turing proved), you wouldn't be able to use a prove for this statement in any way. Undecidability is very different from the P=NP problem.)

See also [here](https://news.ycombinator.com/item?id=12352169).

**Comment by robconery** [comment]
Thanks for the lengthy comment - it's a lot to wade through. I've seen multiple assertions that the halting problem is NP-hard (I'm not near my machine just now... I'll find my sources in a sec) - if I'm to change things, especially on this, I would need to see something convincing that I can pass on.

So, let me chew through what you wrote here but, if you have more, hit me :).

I have to say that using the word _provably_ in an NP discussion is scary.

**Comment by racko** [comment]
Damn, you are right about [the halting problem being NP-hard](http://stackoverflow.com/questions/6990683/proof-that-the-halting-problem-is-np-hard). I had to refresh my knowledge in that area yesterday night and argued for the halting problem not being NP-complete instead :(

I removed the issues about [Boolean satisfiability](https://github.com/imposters-handbook/feedback/issues/90), [the lambda calculus example](https://github.com/imposters-handbook/feedback/issues/92), [the lambda calculus evaluation order](https://github.com/imposters-handbook/feedback/issues/91) and [NP-hard and Undecidability](https://github.com/imposters-handbook/feedback/issues/93) so they can be discussed separately.

In this thread I am left to argue that you should find the confidence to remove the two "likely"s, "though nobody knows for sure" and "The truth is we just don't know".

Please have a look at the Cook-Levin theorem. Basically it provides an efficient algorithm for solving any NP problem, provided that you already have an efficient algorithm for the Boolean satisfiability problem. So (the proof for the) the Cook-Levin theorem is the proof in "They can provably be cracked if we crack the Boolean satisfiability problem". It's not that scary ;)

What we really don't know about NP-complete problems is whether there are polynomial time algorithms for them. That's where you can (and should) write that "we just don't know". But the consequence of finding a polynomial time algorithm for any NP-complete problem is without a doubt that we can use it to solve any other NP problem in polynomial time, too.

**Comment by maebeale** [comment]
I got confused at first which examples were for which, and not having seen
all of the notations before had to keep flipping to compare/contrast the
actual notation, definition and example. Maybe summarize them at outset in
a table or outline, or move the awesome diagram sooner?

(I'd love a table, bc then longer text like the definition could be
included and notations left-aligned for easy visual comparison. I'm reading
through the Kindle app on my Android phone tho, so not getting all the
spatial cues, so take these comments with a grain of salt.)

On Aug 24, 2016 10:28 PM, "Rob Conery" notifications@github.com wrote:

Thanks for the lengthy comment - it's a lot to wade through. I've seen
multiple assertions that the halting problem is NP-hard (I'm not near my
machine just now... I'll find my sources in a sec) - if I'm to change
things, especially on this, I would need to see something convincing that I
can pass on.

So, let me chew through what you wrote here but, if you have more, hit me
:).

I have to say that using the word _provably_ in an NP discussion is scary.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/imposters-handbook/feedback/issues/83#issuecomment-242264861,
or mute the thread

**Comment by robconery** [comment]
Perfect - this is a _super_ tough subject and I really, really appreciate all the help and feedback!

**Comment by robconery** [comment]
OK @racko I'm working through this some - I did read Cook-Levin a bit and also [Karp's 21 NP-Complete Problems](https://en.wikipedia.org/wiki/Karp%27s_21_NP-complete_problems) and i think your last statement might have cleared something up for me:

> What we really don't know about NP-complete problems is whether there are polynomial time algorithms for them. 

I _think_ I am conflating "solving" with "in P" - I think I get your point. Maybe :).

**Comment by robconery** [comment]
OK - here's a quick edit:

What if we could, however, ask the computer a simple question:

> What values for `x` and `y` would make this conditional statement evalue to `true`?

This is the Boolean Satisfiability Problem. If we can crack this, we can solve the NP-Complete puzzle by way of _reduction_ (see Karp's NP-Complete problem list above). In fact we can solve _all of NP_, which is mind-melting.

The only thing we _won't know_ is if solving SAT can be done in P time. If it can, then yes: P = NP. 

So get to work!

**Comment by robconery** [comment]
I've rewritten the chapter and agree with @racko... updated and will be sent out later today.
