### ISSUE TITLE
PDF p. 30, "trog"

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#84]
On PDF p. 30:

> You   can say "Linux" and still   be  OK, as  they'll know    what    you mean,   but they'll think
> you're  a   bit of  a   trog.

Is "trog" a typo?  One dictionary defines a trog as a "a hooligan; lout.", which doesn't seem to fit.  It could also be a shortened form of "troglodyte," but the sentence doesn't make sense to me with that meaning, either.

**Comment by fedgrant** [comment]
Right under this it says operating system that GNU\/Linux. Has a extra '\'.

**Comment by robconery** [comment]
Trog == troglodyte == caveman. Slang in some parts of the world.
