### ISSUE TITLE
More Readable Typeface?

### ISSUE THREAD

**Issue by kaler** [robconery/feedback#85]
Is it possible to have the book set in a more readable typeface?  Preferably serif over sans-serif.

Amazon Kindle uses Bookerly by default.  The last iBook that I read was set in Iowan.  Times New Roman is the classic go to typeface for reading.

**Comment by robconery** [comment]
Can you not choose a font to use? Or maybe load the PDF version? I don't know Kindle.

**Comment by wconrad** [comment]
For Kindle, you can set the font.  For PDF, you can't.  I would prefer a serif font for the PDF version, but it's not a huge deal.

**Comment by robconery** [comment]
I see - I'll see what I can come up with. Font choice always makes people jumpy.
