### ISSUE TITLE
PDF p. 65 typo: missing comma in '"...every day of the week" as the stars...'

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#87]
On PDF p. 65:

> I used        0   0   \*   \*   \*       as  the schedule,   which   reads   "the    first   minute  of  the first   hour    of
> every   day of  the month,  every   month,  every   day of  the week"   as  the stars   are
> wildcard    characters.

'...day of the week" as the stars are wildcard characters.' should have a comma: '...day of the week," as the stars are wildcard characters.'

**Comment by robconery** [comment]
I put the last part of the sentence (the non-quoted) in parens to read better.
