### ISSUE TITLE
PDF p. 82: Incomplete regular expression

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#88]
On PDF p. 82:

> We're using   a   regular expression      ^[:alnum:]   ,  which   means   "anything   not alpha-
> numeric"    (   :alnum:     is  short   for alpha-numeric   if  you haven't guessed that).  The full
> expression  says    "search globally    for anything    not alpha-numeric   and replace it  with
> a       -    ":     s/[^[:alnum:]]/-/g   .

I think there is a typo here, as the regular expression is `[^[:alnum:]]`, not `^[:alnum:]`.  Without the outer square brackets, the meaning is quite different.

**Comment by robconery** [comment]
Thank you! Fixed...
