### ISSUE TITLE
PDF p. 91, typo `is_rsa.pub`

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#89]
On PDF p. 91:

> This  key can be  your    personal    SSH key found   in      ~/.ssh/is_rsa.pub    ,  or  it  can be
> saved   in  a   PEM file    that    you pass    along.  Whichever   you choose  is  up  to  you.

The filename `is_rsa.pub` should be `id_rsa.pub`.

**Comment by robconery** [comment]
Thanks!
