### ISSUE TITLE
Missing command to install Oh My Zsh

### ISSUE THREAD

**Issue by JoshuaCarmody** [robconery/feedback#9]
In the chapter "Linux: Oh My ZSH!", the following instructions for installing Oh My Zsh are given:

> Installation is simple - let’s just do it:
> -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

I believe that command should be:

`sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`

The book is missing the "sh" part of the command, and includes only the argument.

**Comment by robconery** [comment]
Thank you! You sir just got yourself a refund! Seriously: thank you so much. Great catches...
