### ISSUE TITLE
Boolean Satisfiability

### ISSUE THREAD

**Issue by racko** [robconery/feedback#90]
The Boolean satisfiability problem is not about evaluating an if statement.

I want to make the difference clear with an example: Given the Boolean expression "a AND NOT b", you can evaluate the expression in an if-statement if you are told additionally that, e.g., a = true and b = true:

```
a AND NOT b
= true AND NOT true
= false,
```

so you have to take the else branch of the if-statement. This problem is solvable in linear time.

The Boolean satisfiability problem is about finding values for a and b such that the expression evaluates to true. In this case you want to find "a = true, b = false" because then

```
a AND NOT b
= true AND NOT false
= true AND true
= true.
```

**Comment by robconery** [comment]
Right - I think I muddled the explanation. I used an `if` statement as a way to ground the idea but I clearly need more explanation there.

**Comment by robconery** [comment]
OK - I've edited it thus (and many thanks by the way, you made something click heavily in my head):

Think about the longest, most ridiculous `if` statement you've ever written, maybe something like (pseudo code):

```
if ((x and y) and (x and not y)) or ((x or y) and (x or not y)) then 
//...
```

For a computer to evaluate this for `x` and `y`, values for both (let's say `true` or `false`) need to be plugged in and the statement evaluated in a linear way.

What if we could, however, ask the computer a simple question:

> What values for `x` and `y` would make this conditional statement evalue to `true`?

This is the Boolean Satisfiability Problem. If we can crack this, we can (possibly) crack the NP-Complete puzzle.

If NP-Complete problems get resolved, it's likely (though nobody knows for sure) that we'll crack _every_ NP problem. Which is rather huge.

The truth is we just don't know.
