### ISSUE TITLE
Lambda Calculus evaluation order

### ISSUE THREAD

**Issue by racko** [robconery/feedback#91]
The lambda calculus is not "reduced from left to right". It can be reduced in any order. [Normal order evaluation](https://en.wikipedia.org/wiki/Evaluation_strategy#Normal_order) is only one (useful) evaluation strategy among many.

Maybe you mean "Applications are assumed to be left associative: M N P may be written instead of ((M N) P)" ([Wikipedia](https://en.wikipedia.org/wiki/Lambda_calculus#Notation)), but that is a different statement.

**Comment by robconery** [comment]
This was removed - thanks :).
