### ISSUE TITLE
Lambda Calculus Example

### ISSUE THREAD

**Issue by racko** [robconery/feedback#92]
(\x. x x)(\x. x x) does not beta-reduce to (x x)(\x. x x). (\x. x x)(\x. x x) -> (x x)[x:=(\x. x x)] is correct, but the intermediate step (\x. x x)(\x. x x) -> (x x)(\x. x x) is, in general, not (or I misinterpret your notation.) Could you explain your derivation?

**Comment by robconery** [comment]
I can't tell what you're referencing here...

**Comment by robconery** [comment]
Never mind - found it! YES I totally biffed the substitution step. Thanks :). Fixed!
