### ISSUE TITLE
Typo in linux chapter

### ISSUE THREAD

**Issue by href** [robconery/feedback#94]
At the beginning of the linux chapter you write “**Breath** in. Smell the pines, hear the birds”.
I think it should say "**Breathe** in" instead.

**Comment by jbellars** [comment]
Agreed. I saw that too. http://en.bab.la/conjugation/english/breathe 
_Page 25:_ s/Breath in/Breathe in/

**Comment by robconery** [comment]
Thanks! Fixed.
