### ISSUE TITLE
Remove uuid-ossp from Postgres packages

### ISSUE THREAD

**Issue by bdewater** [robconery/feedback#95]
From https://www.postgresql.org/docs/9.5/static/uuid-ossp.html:

> Historically this module depended on the OSSP UUID library, which accounts for the module's name. While the OSSP UUID library can still be found at http://www.ossp.org/pkg/lib/uuid/, it is not well maintained, and is becoming increasingly difficult to port to newer platforms. uuid-ossp can now be built without the OSSP library on some platforms. On FreeBSD, NetBSD, and some other BSD-derived platforms, suitable UUID creation functions are included in the core libc library. On Linux, OS X, and some other platforms, suitable functions are provided in the libuuid library, which originally came from the e2fsprogs project (though on modern Linux it is considered part of util-linux-ng). When invoking configure, specify --with-uuid=bsd to use the BSD functions, or --with-uuid=e2fs to use e2fsprogs' libuuid, or --with-uuid=ossp to use the OSSP UUID library. More than one of these libraries might be available on a particular machine, so configure does not automatically choose one.
> 
> **Note:** If you only need randomly-generated (version 4) UUIDs, consider using the gen_random_uuid() function from the pgcrypto module instead.

Given the note I think it's safe to remove uuid-ossp and move the mention of GUIDs to the pgcrypto bullet point.

**Comment by robconery** [comment]
Thanks!
