### ISSUE TITLE
PDF p. 157, missing/invisible characters near "I can rename x to be"

### ISSUE THREAD

**Issue by wconrad** [robconery/feedback#96]
On pdf P. 157, there are missing/invisible characters near "I can rename x to be":

http://imgur.com/a/OxMUK

**Comment by robconery** [comment]
Whack - I'm going to move the entire thing to a new editor so hopefully this will resolve.

**Comment by robconery** [comment]
LOL oops! Looks like UTF-8 isn't supported with Gitbook. This will be fixed for next drop as I'm moving to Scrivener.
