### ISSUE TITLE
mv ... /dev/null cartoon

### ISSUE THREAD

**Issue by joshcrews** [robconery/feedback#97]
I am so afraid someone is going to type that code in the cartoon into their terminal.  Maybe only 1 in 1,000, but that might effectively "total" a computer for some people

![Uploading Screen Shot 2016-08-25 at 9.05.02 AM.png…]()

**Comment by wconrad** [comment]
This may be a duplicate of https://github.com/imposters-handbook/feedback/issues/30

**Comment by robconery** [comment]
I don't see the image you're referring to?

**Comment by joshcrews** [comment]
yes, duplicate of #30
