### ISSUE TITLE
pdf Page 41 example error

### ISSUE THREAD

**Issue by jtbarker** [robconery/feedback#98]
Permissions example reads:  drwxr-xr-x

The example explained says the public can only execute.  In fact this example allows the public to read and execute.  Thank you in advance for the refund!

**Comment by robconery** [comment]
Yeah I goofed that explanation :). Are you asking for a refund or are you joking?

**Comment by jtbarker** [comment]
Not joking!  Wasn't that the deal?   Anyway the book is great, thanks for writing it.

**Comment by robconery** [comment]
Hmmm - well the idea was "making a difference" which I suppose we could argue that this _does_ but I was thinking something a little more substantial... I should probably flesh that out some. 

All of this is moot, however, since this is a duplicate :(

**Comment by jtbarker** [comment]
OK, fair enough.  Keep up the great work and thanks for writing!
